### ISSUE TITLE
Spike: [M] OAI-PMH feed needs to show OA status for Plan S

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#104]
# Glossary

VoR :: Version of Record
AAM :: Author Accepted Manuscript

# Summary
OA status - Open access data; shows whether the files attached to the work are open or restricted (Visibility per file status)

Machine readable information on the open access status and licence embedded in the article - requirement of Plan S repositories.
The licence of files as well as works should also be available. 

A non-proprietary format is an open data format that can be accessed and read by either open or paid for software. Non-proprietary machine-readable formats include JSON and XML.

Most repository software platforms have this capability built in. However, cOAlition S recognises that some, particularly smaller publishers and some repositories, are not currently set up to facilitate this. In these cases, metadata describing the open access status of the work and the licence assigned to it must be included in the item description metadata (such as repository item record or webpage metadata for the item). Such item metadata should be in a common, non-proprietary format, and machine-readable. 

If the repository platform provider can accommodate this specific embedded machine-readable information, ensure that all the relevant metadata fields are completed for the system to retrieve the required data and surface it as machine-readable information.

Provide and advocate depositing metadata standards for repository users to encourage a consistent metadata flow.

[Technical Guidance and Requirements](https://www.coalition-s.org/technical-guidance_and_requirements/) 

# Sub Tasks

- [ ] The OAI-PMH XML feed from the site needs to include the open access indicator for the work; that involves reading the tech guidance.
- [ ] Implement the logic to determine the value for the above feed element

# Accepted Criteria

- [ ] files licence and works are available in a JSON or XML format

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by jeremyf** [comment]
Note, the technical team met earlier to share context and lay out recommendations of what that looks like.  @cziaarm will be reaching out to @j-basford for some additional information.

**Comment by jeremyf** [comment]
This is slated for [2022-12-06 discussion](https://docs.google.com/document/d/1fcmEKyazxeL3NSRR607xJ1u9I7eFMvF0Qdyq4lHLbeg/edit#heading=h.3zeglegwljh)

**Comment by cziaarm** [comment]
@j-basford (and also @jeremyf),

Once the open access-i-ness of our record has been established. We will need to express this status in a machine readable way. This task assumes that OAI-PMH is the way to do that, and there is a good argument for that. However just to note that OAI-PMH doesn't _have_ to be the way that we tick the machine-readable plan S box. We can answer that question with resourceSync by ensure that the OA status is expressed in the MR output of our records where appropriate (https://bl.iro.bl.uk/concern/articles/5487ebc4-c860-43f2-b0e6-acc4900ec564?format=json).

Another consideration to throw in to the mix is Openaire which represents a useful standard when we are looking at euro-wide-compliance frameworks. (https://guidelines.openaire.eu/en/latest/literature/use_of_oai_dc.html) It may be worth considering openaire as a separate metadataprefix and going the whole hog.

So with these considerations here are options for expressing the our records' OA status.

Options here (that I can think of):

- Overriding the provider code for the oai_dc metadataPrefix to express OA status in <dc:rights>
- As above but using openaire compliant syntax <dc:rights>info:eu-repo/semantics/openAccess</dc:rights>
- A new metadataprefix oai_openaire with dc:rights and all the other metadata epressed in an openaire compliant way
- forget the above, use resourceSync, override work_show_presenter or some such.

**Comment by cziaarm** [comment]
A quick search for openaire _and_resourceSync gave me this from 2018: 

"[ResourceSync](http://www.openarchives.org/rs/toc) is a synchronization framework for the web consisting of various capabilities that allow third-party systems to remain synchronized with a server's evolving resources. As a successor of the OAI-PMH protocol it is faster, reliable, scalable and allows real-time notification (and recovering of missed messages). 4Science has releasead a ResourceSync implementation for DSpace 5, 6 and (future) 7 with the support from OpenAIRE."

We don't know if that support materialised or which way round they mean (openaire consuming resroucesync or openaire publishing using resourceSync). So not sure that would be an option, but it would be good if it was

**Comment by laritakr** [comment]
Tasks:
- [ ] Add new property to the work types which may be peer-reviewed: [Article , Conference Item , Generic Work] https://github.com/scientist-softserv/britishlibrary/issues/330
- [ ] Add open access term to feed - requires some analysis regarding direction: OAI or json (or both if basically same amount of work) https://github.com/scientist-softserv/britishlibrary/issues/331
