### ISSUE TITLE
[M] Upgrade Bulkrax to v3+ [may already be complete]

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#118]
# Summary

This is not a request from the client. 

Ref this slack convo for details: https://assaydepot.slack.com/archives/G030UPFBT2S/p1654787124914259

At the moment of creating this ticket, BL is pointing to its own branch of bulkrax (based off of 3.1.2)

**Comment by jeremyf** [comment]
Prior to 2022-12-01, the repository was on v3.3.0 of Bulkrax which should resolve the issue.  With #204 this should be the safe and straightforward upgrade.

In a strict reading of the ticket, I believe this is resolved.

**Comment by DiemBTran** [comment]
Deon is upgrading from v3.5 to v4.4.
