### ISSUE TITLE
[C] Footer references Notch8.com should be Software Services by Scientist.com (or SoftServe etc)

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#126]
No Value

**Comment by jillpe** [comment]
Passes internal QA



![Image](https://user-images.githubusercontent.com/84697174/210442672-c95d8916-ec12-4a5a-b1c2-e3c60d7b0f1e.png)

**Comment by grahamjevon** [comment]
Tested shared page and tenant pages (logged in and logged out). "Software services ..." has replaced "Notch 8" as expected in footer.

**Comment by grahamjevon** [comment]
Appears as expected on production.
