### ISSUE TITLE
[M] add shared repo logo to IRO homepage

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#128]
# Summary

Implement the wireframe for this page: 

- [ ] production: https://iro.bl.uk/
- [ ] staging: https://bl-staging.notch8.cloud

# Details

Just for the shared page - it is already included as the logo on the shared search tenant. 

See thread here: https://assaydepot.slack.com/archives/G0313NK2LJ0/p1662470710913919

Shared Repo logo to appear somewhere logical on the homepage of the repository.
Two variants (attached) with or without text.

![Image](https://user-images.githubusercontent.com/29311858/201790464-24b1f4fd-6651-47d1-8476-5d15fe49b19a.png)

![Image](https://user-images.githubusercontent.com/29311858/201790484-c392857f-5618-49e5-9dbf-0760aade498d.png)

One of Summer's mockups:

![Image](https://user-images.githubusercontent.com/29311858/201790500-bc80533f-75c3-4f50-ace7-3e6d62f09ce2.png)

**Comment by jillpe** [comment]
Passes internal QA

Logo shows for both logged in and logged out users

**Comment by grahamjevon** [comment]
Shared logo appears as expected on production.
