### ISSUE TITLE
Update Homepage Credit to SoftServ

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#131]
The homepage at https://iro.bl.uk/ kindly credits Notch8 and CoSector, which hyper links to the websites.  
![Screen_Shot_2022-10-12_at_9.45.14_AM](/uploads/c1b4ee3f0bbc22a07627d4633ff70a3a/Screen_Shot_2022-10-12_at_9.45.14_AM.png)

Please update:

- [ ] "Notch8" to "SoftServ"
- [ ] Change link to go to https://softserv.scientist.com/

**Comment by jillpe** [comment]
closed - duplicate
