### ISSUE TITLE
Add to collection button does not respond

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#133]
Update for 2023-01-30: The purpose of this spike is to determine if this is a maintenance issue (and thus something for @cziaarm) or if this is something that SoftServ introduced.

Regardless the details below should help in resolution.  

## Original Details

In admin view of a collection, 'add to collection' button should allow an admin user to move a work into that collection. Currently nothing happens. 

![Image](https://user-images.githubusercontent.com/11359350/196323352-77fe8609-811e-47cc-8074-a6ba02066220.png)

# Testing Instructions
- [ ] Navigate to the homepage
- [ ] Click View All Collections
- [ ] Choose a collection to open the collection show page
- [ ] Click add to collection button
- [ ] Add collection to another collection

**Comment by jeremyf** [comment]
Looking at the browser, we see that there’s an error for `buildSelectMarkup` ([see code](https://github.com/samvera/hyrax/blob/cff1ddd18764e4d14a2404d61d20ae776ea62916/app/assets/javascripts/hyrax/collections.js#L73-L79)).

    function buildSelectMarkup(collsHash) {
      var options = collsHash.map(function(col) {
        return '<option value="' + col.id + '">' + col.title_first + '</option>';
      });
      var markup = options.join('');
      return markup;
    }

Which is called at the following location ([see code](https://github.com/samvera/hyrax/blob/cff1ddd18764e4d14a2404d61d20ae776ea62916/app/assets/javascripts/hyrax/collections.js#L108-L114)).  This assumes that `$dataEl` has a data attribute (e.g. `data-collsHash`).

    addDataAttributesToModal('#add-to-collection-modal', ['id', 'post-url'], $dataEl);
    // Grab reference to the default <option> in modal
    $firstOption = $('#add-to-collection-modal').find('select[name="parent_id"] option');
    // Remove all previous <options>s
    $firstOption.not(':first').remove();
    // Build new <option>s markup and put on DOM
    selectMarkup = buildSelectMarkup($dataEl.data('collsHash'));

And if we look at where we set `$dataEl` ([see code](https://github.com/samvera/hyrax/blob/cff1ddd18764e4d14a2404d61d20ae776ea62916/app/assets/javascripts/hyrax/collections.js#L89-L93))

    $dataEl = (
      $self.closest('#collections-list-table').length > 0 ?
      $self.closest('tr') :
      $self.closest('section')
    ),

This defines the `$dataEl` and is highly dependent on the DOM structure; Note the ID defines if we’re looking for an a nearby `TR` tag or an nearby `SECTION` tag (no dom classes for scoping).  This looks very fragile.  And in the web inspector, when we looked at the at the button, there was no `#collections-list-table` which meant we’d be looking for a `SECTION` tag.  But there was no `SECTION` tag, which meant that `$dataEl` was `undefined`.

    ❯ cd ~/git/hyrax; rg "id=['\"]collections-list-table"
    app/views/hyrax/dashboard/collections/_default_group.html.erb
    1:<table id="collections-list-table" class="table table-striped collections-list-table">
    
    app/views/hyrax/my/collections/_default_group.html.erb
    1:<table id="collections-list-table" class="table table-striped collections-list-table">

**Next Steps:** We should look for a Hyku override in British Libraries to see if the UI broke this.  We may need to look at `app/assets/javascripts/hyrax/collections.js`.

**Comment by ShanaLMoore** [comment]
todo: compare with other projects. Adventists' button works. Try to locate the diff between them. @DeonFranklin to pair with @AKFosterDev

**Comment by ShanaLMoore** [comment]
Maintenance issue? 

Did changing the UI without updating the javascript, break this? 

What is the page that gets rendered and the git history? 

We will turn this into a spike ticket until we can answer the above questions. This ticket will close once we decide if it's a maintenance issue or not.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested with:
- https://bl.bl-staging.notch8.cloud/collections/7cd6577c-562f-471a-8465-a42fd80e6ad8?locale=en
- https://bl.bl-staging.notch8.cloud/collections/afbdbaf4-3c39-4e9d-809c-c60170cbb91a?locale=en

<details><summary>"Add to collection" button allows a user to add the current collection to another collection. The current collection then becomes a child of the second collection.</summary>


https://user-images.githubusercontent.com/29311858/215904563-5afc425f-1fdb-439e-a4c1-512f1ce9b00c.mp4</details>

**Comment by j-basford** [comment]
behaves as intended

**Comment by grahamjevon** [comment]
Behaves as expected in bl-demo
