### ISSUE TITLE
10c IRUS counter Ruby gem to be integrated (req. 1.10c)

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#136]
Please integrate IRUS counting for each of the live repositories, including the NHS (not any of the demo tenants). This can be included as work on analytics which is the last milestone.

Tender context: 'We also need the repositories to work with IRUS-UK, the UK’s central provider of COUNTER-conformant usage data for repositories.'

CS/N8 response: 'This parameters and function of this requirement are well known to us from other platforms. This feature can be added using the irus_analytics gem developed specifically for this task. The gem is old so we will assess its readiness for inclusion with the latest version hyrax and it's compliance with current IRUS/Counter requirements.'

Paul Needham at Jisc (who run IRUS) spoke with Michigan about if the gem should work: 'most likely it is a yes as it is a ruby gem and works with Hyrax. Hyku's foundation is also Hyrax so it should work. It would be good to experiment and see how it works.'

**Comment by cziaarm** [comment]
My IP is 81.174.241.126

![Image](https://user-images.githubusercontent.com/1931982/201203029-c38bc8aa-a265-47c9-babf-8a30035cf689.png)

**Comment by j-basford** [comment]
Emailed Paul Needham at Jisc 14/11/22 for feedback
