### ISSUE TITLE
[S] DOI minting outstanding niggle - not mapping resource type for Book quite accurately

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#139]
Items with Hyku resource type 'Book' are being sent to DataCite as ResourceTypeGeneral = Other and ResourceType = Book.

This means it shows as both 'Other' and 'Book' - but as there is a ResourceTypeGeneral = Book - it should map to that and ResourceType = Book.

![Image](https://user-images.githubusercontent.com/11359350/196327358-41c8cb80-5da9-492d-bea6-090174fbba37.png)

![Image](https://user-images.githubusercontent.com/11359350/196327367-1036fe55-1cc7-43be-8e4a-40fb859da825.png)

**Comment by cziaarm** [comment]
https://github.com/scientist-softserv/britishlibrary/pull/165

**Comment by j-basford** [comment]
https://doi.test.datacite.org/dois/10.21220%2Fqf4b-px81 - this is still showing Other in the RTG for me when using Book worktype and should be showing Book in RTG?

Test work: https://bl-demo.iro.bl.uk/concern/books/64a8e6d6-20e8-4a43-bcda-183c8485b4f0?locale=en 



![Image](https://user-images.githubusercontent.com/117307899/200417714-d2b8c369-20cb-4e56-81dc-b258b3914111.JPG)

**Comment by j-basford** [comment]
scratch that, works great when actually tested correctly in staging not production

**Comment by j-basford** [comment]
Tested with https://doi.datacite.org/dois/10.23636%2Fbb95-hs69 changed from 'other' to 'book' - passes QA
