### ISSUE TITLE
DOI with findable status created on embargo release is assuming registered status in fabrica

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#140]
This work: https://bl-demo.iro.bl.uk/concern/generic_works/40a100f8-cc8b-47d9-8600-fa88dde8aad1
was created 1/3/22 to release 2/3/22, with a Findable DOI - embargo has released and DOI minted but stuck at Registered not Findable status in Fabrica.

![Image](https://user-images.githubusercontent.com/11359350/196327980-df5ffa79-5cae-44af-a81e-eed7584fa39e.png)

![Image](https://user-images.githubusercontent.com/11359350/196327986-78f9d7d3-510d-4dd6-9487-bcdd712243f1.png)

**Comment by cziaarm** [comment]
@jeremyf A question for you:

When an embargo is deactivated the `EmbargoActor.destroy` is called. The `EmbargoActor` is not in the actor stack (as per `Hyrax::CurationConcern.actor_factory`) It does call `work.save!` but that doesn't appear to go through the actor stack and the upshot is that DOI info is not updated when an embargo is deactivated (hence this ticket)

Now I could replicate this functionality https://github.com/scientist-softserv/britishlibrary/blob/main/app/actors/hyrax/actors/doi_actor.rb#L45-L56 in the EmbargoActor and that would work, but I suspect there might be a more hyrax way to do this?
