### ISSUE TITLE
Resource Type search within a collection issue

### ISSUE THREAD

**Issue by grahamjevon** [scientist-softserv/britishlibrary#170]
Resource Type should be searchable. It is searchable as expected in the main search. But it is not in the search within a collection search function.

For example:

If I enter "Software" in the main search field, the 4th item in the search results is Peripleo (https://bl.iro.bl.uk/concern/datasets/519981d9-bdeb-4c0b-8729-16927d48f517). So far so good.

The Peripleo software is within the Location a National Collection user collection. However, if I first search for "Locating a National Collection", open this user collection (https://bl.iro.bl.uk/collections/a850a76f-5832-41ae-9915-010accc43b43?locale=en), then search for "Software" within this collection, no results are returned.

**Comment by cziaarm** [comment]
Note to self: try overriding params_for_query in app/controllers/hyrax/dashboard/collections_controller.rb
