### ISSUE TITLE
Spike: XML parser using UK ETD_DC but matching EthOS IDs

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#175]
# Summary
This will use the same mappings as UK ETD_DC, where the EthOS ID is the identifier for matching records. This is for when they need to go in and make changes to records that have already been uploaded in the system.

# Accepted Criteria
- [ ] As a cataloguer, I can upload changes to thesis and do not get duplicate records for items that have the same EthOS ID

# Notes
Related to #174  
- The goal is the same as #174, but to be able to update as well

**Comment by ShanaLMoore** [comment]
per jeremy:

assume there's an ethos identifer, when i go to update a record via bulkrax. if the ethos id exsists in hyrax, update the hyrax record w this metadat.

**Comment by jillpe** [comment]
The goal of this ticket is to identify if this is working, and if not, create tickets on what is not working

**Comment by ShanaLMoore** [comment]
https://github.com/scientist-softserv/britishlibrary/blob/main/config/initializers/bulkrax.rb#L225

cc @jeremyf when we look at the source_identifier declared in the bulkrax field mappings, i was expecting the UK ETD_DC parser to be mapped ot ethos id but that doesn't appear to be the case so how can we expect it to update a record?

**Comment by kirkkwang** [comment]
Tested with EThOS_Export_uketd_dc_Sample (1).xml found in https://drive.google.com/drive/folders/1cWEeYiwh9UeLKC4DB2TDHaVETZgWVa6k

1. Create an import
2. Alter the xml
3. Create another import
4. Observe no duplicates and the metadata has been changed

Before:
![Screenshot 2023-03-24 at 10 26 36](https://user-images.githubusercontent.com/19597776/227598317-4deef9a1-8e4d-4f9c-8c0a-6d196e7e55a6.png)


After:
![image](https://user-images.githubusercontent.com/19597776/227598271-801979fa-3172-409c-83fb-4f4b2c0d61a9.png)

**Comment by ShanaLMoore** [comment]
This can be closed since no work needs to be done. Ref Kirk's testing [results](https://github.com/scientist-softserv/britishlibrary/issues/175#issuecomment-1483168333).
