### ISSUE TITLE
<dc:language xsi:type="dcterms:ISO639-2"> XML tag handling

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#178]
# Summary
British Library would like the <dc:language xsi:type="dcterms:ISO639-2"> XML tag for thesis to be mapped to the Hyku field labeled 'Language', however, the language of the thesis is in coded form.

Concern:
How will the coded form translate? 

BL Notes:
Three letter code ISO standard - linked database. eg. eng (lower case)

# Accepted Criteria
- [ ] As a cataloguer, I can map the language of a thesis to the hyku field labeled 'Language' via the <dc:language xsi:type="dcterms:ISO639-2"> tag

# Testing Instructions

- [x] Create an XML Importer
  - [x] Select “XML - ETD_DC Parser”
  - [x] In Record element : uketddc
  - [x] Import Type: Multiple works per Metadata File
  - [x] Use XML file https://drive.google.com/drive/folders/1cWEeYiwh9UeLKC4DB2TDHaVETZgWVa6k
  - [x] Perform create import
- [x] There should be 7 works verify the above tag is found in at least one of the parsed metadata of the importer entries
~~- [ ] Then look at that work in the show page to see that it renders.  It is not a failure if it does not render, but should be noted.  (That is to say parsing the data is the first priority, showing the data is the second)~~
- [x] Then edit that work and see how the field renders in the edit page.

(Note for all but the last step you can re-use the importer for issues #177, #178, #179, #180, #181, #182, #187)

# Notes
- related to #174 and #175

**Comment by j-basford** [comment]
populates as 'eng' in correct field
