### ISSUE TITLE
<dcterms:issued> XML tag handling

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#179]
# Summary
British Library would like the <dcterms:issued> tag for thesis to be mapped to the hyku field labeled 'Date accepted', for the date of the award of the thesis

**Concern:**
Date of the award of the thesis (held as dd/mm/yyyy in the EThOS database but BL only wants the yyyy to display)

# Accepted Criteria:
- [x] As a cataloguer, I can map the year of the award of a thesis to the hyku field labeled 'Date accepted' via the  <dcterms:issued> tag

# Testing Instructions (for rework testing instructions see below)

- [x] Create an XML Importer
  - [x] Select “XML - ETD_DC Parser”
  - [x] In Record element : uketddc
  - [x] Import Type: Multiple works per Metadata File
  - [x] Use XML file https://drive.google.com/drive/folders/1cWEeYiwh9UeLKC4DB2TDHaVETZgWVa6k
  - [x] Perform create import
- [x] There should be 7 works verify the above tag is found in at least one of the parsed metadata of the importer entries
- [x] Then look at that work in the show page to see that it renders.  It is not a failure if it does not render, but should be noted.  (That is to say parsing the data is the first priority, showing the data is the second)
~~- [ ] Then edit that work and see how the field renders in the edit page.~~. This does not work but is reported in issue #253 
- [x] Import using CSV https://drive.google.com/file/d/1eGeZytvU0UNH_vW7LRgTq8DtT8-51YSo/view?usp=share_link and then verify you are able to view work & edit work. 

(Note for all but the last step you can re-use the importer for issues #177, #178, #179, #180, #181, #182, #187)

# Rework Testing Instructions

- [ ] Go to a Thesis or Dissertation work such as [this](https://mola.bl-staging.notch8.cloud/concern/thesis_or_dissertations/a26e3942-ba60-40f5-a43e-9084c68ec0d1)
- [ ] Observe that the `Date accepted` field only displays the year
- [ ] Go to a non-Thesis or Dissertation work
- [ ] Add the `Date accepted` property if it does not exist, make sure it is the full date and not just the year
- [ ] Go to the show page for that work
- [ ] Observe the `Date accepted` field is the full date and not just the year

# Notes
- Related to #174 and #175

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://bl.bl-staging.notch8.cloud/importers/24
- https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/8c42d10c-3cc7-47cc-8cfd-c7387775edaa?locale=en

<details><summary>The importer's first work has "date accepted"</summary>

![Thesis Or Dissertation Quantitative dopamine imaging in humans using magnetic resonance and positron emission tomography ID 8c42d10c-3cc7-47cc-8cfd-c7387775edaa Hyku 2023-01-18 at 12 00 07 PM](https://user-images.githubusercontent.com/29311858/213304417-ef4f9845-7ae1-443b-9390-e451596aa715.jpg)
</details>

**Comment by j-basford** [comment]
https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/a3e35bfe-88bd-43da-970b-8fdaf2865cc3?locale=en behaves as expected

**Comment by j-basford** [comment]
https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/8c42d10c-3cc7-47cc-8cfd-c7387775edaa?locale=en - this one has accepted date 1/1/2014 but this doesn't show in the metadata (on either show work page or the edit page). date accepted works for all the others.
Returning with needs rework just to have some cast another eye over it

**Comment by laritakr** [comment]
Note: This breaks CSV imports which contain only the year. Needs to be re-evaluated. I moved back to "ready for development".

**Comment by laritakr** [comment]
Additionally, an error also appears here when using the CSV import. If a date is not in the CSV, it imports as [""] and calling empty on this array returns false. 

![Screenshot 2023-03-24 at 12 46 30 PM](https://user-images.githubusercontent.com/17851674/227597012-6d758ebb-d145-42e5-980f-604404368109.png)

Solution: 
![Screenshot 2023-03-24 at 1 25 08 PM](https://user-images.githubusercontent.com/17851674/227597349-902ae280-002e-4992-833a-4f5d98fc0683.png)

**Comment by laritakr** [comment]
Note: the date needs to be able to work correctly for either just a year or a full date.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- XML importer: https://bl.bl-staging.notch8.cloud/importers/55?locale=en
- XML imported work's parsed metadata: https://bl.bl-staging.notch8.cloud/importers/55/entries/897?locale=en
- CSV importer: https://bl.bl-staging.notch8.cloud/importers/57?locale=en
- CSV imported work's show page: https://bl.bl-staging.notch8.cloud/concern/reports/469a7711-8c4f-4d18-9ea6-f54871cb92f9?locale=en

<details><summary>XML importer shows the date_accepted in its parsed metadata. On its work show page, only the year renders for the "Date accepted". CSV imported work can be viewed and edited.</summary>

![Show Entry BL Staging 2023-04-05 at 11 16 30 AM](https://user-images.githubusercontent.com/29311858/230169926-91d9606e-f960-4ea3-933f-e5586d4984d8.jpg)
![Thesis Or Dissertation A mixed methods study of the early development of childhood overweight and obesity understanding the process of infant feeding ID c8914471-3285-4333-987a-0e8e3e9ee279 Hyku 2023-04-05 at 11 16 38 AM](https://user-images.githubusercontent.com/29311858/230169936-f6e86f0a-10ea-438d-ad0a-080be8de4842.jpg)
![Report Report with one file url ID 469a7711-8c4f-4d18-9ea6-f54871cb92f9 Hyku 2023-04-05 at 11 20 00 AM](https://user-images.githubusercontent.com/29311858/230169945-4fdc2e00-4046-4963-b103-522d8c2edda4.jpg)
![Report Report with one file url edited ID 469a7711-8c4f-4d18-9ea6-f54871cb92f9 Hyku 2023-04-05 at 11 17 18 AM](https://user-images.githubusercontent.com/29311858/230169951-fc26eceb-7070-4fe4-a6e9-dff59a03397a.jpg)

</details>

**Comment by ShanaLMoore** [comment]
Blocked until we've reconcile prod with staging deploys. ref #376

**Comment by ShanaLMoore** [comment]
unblocked, if tested in staging.

**Comment by grahamjevon** [comment]
Does not pass BL QA. In the summary above it says:

_"Concern:
Date of the award of the thesis (held as dd/mm/yyyy in the EThOS database but BL only wants the yyyy to display)"

This concern is specific to Ethos. For theses and dissertations work types, we only want to display yyyy for the date accepted field. But for all other work types we want the full date to be displayed (as it currently is on production). For theses and dissertations I think we only need to store yyyy in the date accepted field.

**Comment by jillpe** [comment]
2023-05-09: Client confirmed we can store the dd/mm/yyyy and display yyyy on theses and dissertations. https://assaydepot.slack.com/archives/C0313NK2LJ0/p1683651596395499?thread_ts=1683576528.614219&cid=C0313NK2LJ0

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- thesis or dissertation: https://mola.bl-staging.notch8.cloud/concern/thesis_or_dissertations/a26e3942-ba60-40f5-a43e-9084c68ec0d1
- non thesis or dissertation: https://mola.bl-staging.notch8.cloud/concern/images/d7236223-3bc8-4c7b-a171-d100059d3f6b?locale=en

<details><summary>Thesis/dissertation only shows the year for "Date Accepted". Other work types show the full date.</summary>

![Properties of expanding universes Thesis Or Dissertation  a26e3942-ba60-40f5-a43e-9084c68ec0d1  MOLA 2023-05-10 at 11 30 18 AM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/83c151f7-b878-455c-9862-dc349775dbe5)
![Image jpg only ID d7236223-3bc8-4c7b-a171-d100059d3f6b Hyku 2023-05-10 at 11 30 41 AM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/56c99f29-d8a4-4d5d-95d1-e90654c25ef0)
</details>

**Comment by grahamjevon** [comment]
Passes BL QA - every work type stores full date accepted date. Every work type displays full date accepted date except "Thesis/Dissertation", which displays only the year.

**Comment by grahamjevon** [comment]
Contrary to my previous comment, this does not pass BL QA.

When a thesis/dissertation "date accepted" fields only includes a month/year, no date is displayed in the record metadata for date accepted. Issue identified with [this work](https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/943e3588-8fd3-4b93-a106-7dae86071702?locale=en).

**Screenshot of work being added with only month and year entered into date accepted field**

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/e8ad1a68-6411-42d1-beed-5f9a67e6f12c)

**Screenshot of record metadata with date accepted heading displayed, but the year not displayed. We would expect the year to be displayed**

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/fa756cdf-1abc-4adc-abfe-503f11d89291)

**Screenshot showing that after clicking on "Edit", I can see that the date accepted is no longer stored.**

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/bd764ff9-825d-444d-8ede-20da133f9223)

**Comment by ShanaLMoore** [comment]
@grahamjevon Could you list all of the date formats we should account for? From your example, it seems like a user should be able to save just the month/year. Should they also be able to just save the year, and/or other combinations? This will help us catch all the edge cases. 

Thanks!

**Comment by grahamjevon** [comment]
Hi @ShanaLMoore , all of the following date formats should be available:

- year
- month and year
- date, month, and year
- no date

Regarding the bug, I wonder if this is related or similar to #300 or #176 (I'll repeat this comment in #409)

**Comment by jillpe** [comment]
Slack thread for rework behavior:
https://assaydepot.slack.com/archives/C0313NK2LJ0/p1687256566454929
