### ISSUE TITLE
<uketdterms:sponsor> XML tag handling

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#182]
# Summary
British library would like to map the names of the funding/sponsoring body/bodies to the hyku field labeled 'Funder Name' via the <uketdterms:sponsor> XML tag. 

if there are multiple funders they are separated by “space;space”; the names are not fully “controlled” but an attempt has been made to normalise/standardise where possible; if harvested data contains a sentence about the funders, this has been edited to just the names of the funders

**Concern**
Seperated by double spaces

**BL Notes**
could this match with crossref funder reg

# Accepted Criteria
- As a cataloguer, I can map the names of the funding/sponsoring body/bodies to the hyku field labeled 'Funder Name' via the <uketdterms:sponsor> XML tag

# Testing Instructions

- [x] Create an XML Importer
  - [x] Select “XML - ETD_DC Parser”
  - [x] In Record element : uketddc
  - [x] Import Type: Multiple works per Metadata File
  - [x] Use XML file https://drive.google.com/drive/folders/1cWEeYiwh9UeLKC4DB2TDHaVETZgWVa6k
  - [x] Perform create import
- [x] There should be 7 works verify the above tag is found in at least one of the parsed metadata of the importer entries
- [x] Then look at that work in the show page to see that it renders.  It is not a failure if it does not render, but should be noted.  (That is to say parsing the data is the first priority, showing the data is the second)
- [x] Then edit that work and see how the field renders in the edit page.

(Note for all but the last step you can re-use the importer for issues #177, #178, #179, #180, #181, #182, #187)

# Notes
- Related to #174 and #175

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://bl.bl-staging.notch8.cloud/importers/24
- https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/8c42d10c-3cc7-47cc-8cfd-c7387775edaa?locale=en

<details><summary>The importer's first work has a funder name</summary>

![Thesis Or Dissertation Quantitative dopamine imaging in humans using magnetic resonance and positron emission tomography ID 8c42d10c-3cc7-47cc-8cfd-c7387775edaa Hyku 2023-01-18 at 11 56 37 AM](https://user-images.githubusercontent.com/29311858/213285829-20027256-ffae-4092-9f9e-be797c3c51be.jpg)
</details>

**Comment by j-basford** [comment]
Behaves as expected. We will potentially need a further ticket to finesse this as acronyms are used etc for funder name (as noted above, priority here is getting data in)

AHRC https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/1d108f2a-01bf-4fa1-8683-3eade5530d75?locale=en

BBSRC and GSK: https://bl.bl-staging.notch8.cloud/concern/thesis_or_dissertations/8c42d10c-3cc7-47cc-8cfd-c7387775edaa?locale=en

**Comment by j-basford** [comment]
passes verification
