### ISSUE TITLE
<dcterms:accessRights> XML tag handling

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#184]
**NOTE** This was discussed in the [2022-11-29 Client Meeting](https://docs.google.com/document/d/1MxchrogTDPL98nFHzwMjzKhmBi0RqR2_Sh9QQTTd6oI/edit#bookmark=id.mu9j4modlbux) and may likely be an ignored property.  Please read notes and adjust summary/acceptance criteria.

**NOTE** In our [2023-01-31 Client Meeting](https://docs.google.com/document/d/1DhcKcSpaKpy6_IQw4IJ3WfzByOW3eKCYSFy5jczRGEY/edit#) we discussed amending how we handle the accessRights.  The Summary reflects the tasks to complete.

# Summary

The `<dcterms:accessRights>` import field is either `true` or `false` (or absent).  It represents metadata from the *EThOS* system.  As of  <2023-01-31 Tue> it's unclear the long-term functions we'll build on this attribute.

For now we need to:

- [x] Add the `access_rights` property ([see RDF Vocab](https://github.com/ruby-rdf/rdf-vocab/blob/2cd6c40c33879caa948473949d7c168edaca0e19/lib/rdf/vocab/dc.rb#L170-L178)) to the `ThesisOrDissertation` model.
- [x] Map the `<dcterms:accessRights>` to `access_rights` in the XML 
- [ ] Verify if the CSV parser should handle this or not (aka ask @j-basford )
- [x] Adjust the XML Entry spec to verify the parsed metadata
   - [x] Add to [the spec](https://github.com/scientist-softserv/britishlibrary/blob/3c607dd4b4e89a41e5eee01e14b82080b6eb04f5/spec/models/bulkrax/xml_etd_dc_entry_spec.rb) `expect(entry.parsed_metadata.fetch('access_rights')).to eq(["true"])` (note it may be "true" or true)
- [x] Set the property label to "Restricted content from EThOS" (show page)

For running the importer:

- Upload the [EThOS XML](https://drive.google.com/file/d/1LMZhiMCHgaGXBEJCRlyMCnacoppURlab/view?usp=sharing) xml.
- For record element use: `uketddc`
- Importer type: `Multiple works per ...`

<details>
<summary>Previous information detailing previous information</summary>

# Summary
British Library would like to map the XML tag <dcterms:accessRights> to the hyku field labeled 'embargo date'.

Format of data contains either “true” or “false”; if the data is “true” it means the thesis is indefinitely restricted on EThOS, i.e. no access to the content whether or not we hold any content, to prevent any requests for digitisation

Can't supply flag - you can see the metadata but you cannot request the work, content is entirely restricted (not just on EThOS but also on institutional repo); need to identify those ones and give it a 100 year embargo

They can normally grant contractors access but we need to understand how we would create credentials.  This impacts the access rights; the metadata in Hyku will be publicly visible and we want to point to the Ethos record (which would then allow folks to download the digital object).  The Ethos metadata as its own tenant to facilitate a conversation with Ethos as a potential platform replacement of the existing Ethos; doesn’t feed into the shared search of the other tenants and their cultural heritage.  (Ethos has 1M records and the cultural heritage objects is 10K or so).  Ideally would like the Hyku repos to feed into Explore the BL catalog (a Primo implementation).

Key consideration: we want the metadata and to maintain the reference to the ETHOS data; we could then later pull the data down.

Example URL: https://ethos.bl.uk/OrderDetails.do?did=9&uin=uk.bl.ethos.460079

# Accepted Criteria
-  As a cataloguer, I can map the restriction status of a thesis to the hyku field labeled 'embargo date' via the <dcterms:accessRights> XML tag
</details>

# Notes
- Related to #174  and #175

#Testing Instructions
- [x] Navigate to the admin dashboard
- [x] Under repository contents, click Importers
- [x] Create a new importer 
   - Upload the [EThOS XML](https://drive.google.com/file/d/1LMZhiMCHgaGXBEJCRlyMCnacoppURlab/view?usp=sharing) xml.
- For record element use: `uketddc`
- Importer type: `Multiple works per ...`
- [x] Verify Import is successful and ethos_access_rights is displayed on the show page as well as the work edit page.

**Comment by jeremyf** [comment]
@j-basford or @grahamjevon I think we need to discuss this again; namely what we're doing with this field.

**Comment by ShanaLMoore** [comment]
@jeremyf could you clarify the steps/fields needed for one to run an importer locally?

**Comment by ShanaLMoore** [comment]
Sample [importer](https://mola.bl-staging.notch8.cloud/importers/18/edit?locale=en)
![image](https://user-images.githubusercontent.com/10081604/215904052-05af6e22-6473-4653-a862-48546bcd979b.png)

**Comment by kirkkwang** [comment]
Asset from Shana, pass QA

![image](https://user-images.githubusercontent.com/19597776/216677641-516ecf3a-6776-4ecb-885c-19e12c920cf7.png)

https://mola.bl-staging.notch8.cloud/concern/thesis_or_dissertations/36b3fc08-5794-4f8b-a738-9d9525ae6301?locale=en
