### ISSUE TITLE
File for XML mapping

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#185]
# Summary
Files for the XML mappings can be found in either a cloud storage URL or via zip. BL wants it to update on matching to ethos records, and there can be more than one file.

# Accepted Criteria
- [ ] As a cataloguer, I can upload file(s) via the XML parser and update files upon matching the ethos records

# Notes
- Related to #174 and #175

**Comment by jeremyf** [comment]
I marked this as awaiting client feedback because I'm a bit unclear on what we're doing; I want to see if we can walk through this with @j-basford or @grahamjevon to see what they're thinking/wanting and then build from there.

**Comment by jillpe** [comment]
duplicate #174
