### ISSUE TITLE
controlled list for Institution no longer selected with relevant tenant on creation of a work

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#188]
Institution field is a controlled list of each tenant, i.e. British Lib, Kew etc. When creating a work, this field should be pre-selected depending on which tenant you're in, i.e. BL will have British Library selected and so on. This used to happen but has recently stopped. Please reinstate. 
Each tenant (live and demo repos) should have that field pre-selected for the appropriate institution.

**Comment by cziaarm** [comment]
Note to self: This was being done by ./app/helpers/ubiquity/preselect_institution_helper.rb investigate why not now
