### ISSUE TITLE
IIIF Viewer handles Audio

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#194]
# Summary
British Library would like the viewer to be able to handle/provide stable viewing functionality for Audio

# Accepted Criteria
- [ ] Viewer can handle and provide stable viewing for Audio

# Screenshots and Videos

# Testing Instructions

# Notes

https://github.com/scientist-softserv/utk-hyku/issues/175 has a checklist of work that they did.  It can be used as a reference.

**Comment by jeremyf** [comment]
Given https://github.com/scientist-softserv/utk-hyku/issues/175, we need to determine what kinds of upgrades we may need to perform.

**Comment by jillpe** [comment]
closed - work was complete in #214
