### ISSUE TITLE
EPIC: Deploy and configure IIIF server implementation

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#198]
# Summary
This is dependent upon #197 

- [x] #333
- [x] #334
- [x] #335
- [x] #336
- [x] https://github.com/scientist-softserv/britishlibrary/issues/383

# Accepted Criteria

When viewing a iiif manifest in the deployed application, links to images should be pointing at cloudfront instead of at the rails application. Those image urls should render images.

# Screenshots and Videos

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
@cziaarm - please review this message on your return. **https://assaydepot.slack.com/archives/G030UPFBT2S/p1680834741223329**
