### ISSUE TITLE
Spike: Look at more broadly supported libraries that might replace BrowseEverything

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/britishlibrary#207]
The goal is to come back with a effort estimate on an alternate.

Let's look at https://samvera.slack.com/archives/CB750PLNN/p1668024866763329

For example https://github.com/transloadit/uppy/

Note it does not support SharePoint

**Comment by crisr15** [comment]
It does not look like it supports SharePoint, but it does do One Drive which I think is the SharePoint app they were most interested in using.

**Comment by jeremyf** [comment]
On [2022-12-06](https://docs.google.com/document/d/1fcmEKyazxeL3NSRR607xJ1u9I7eFMvF0Qdyq4lHLbeg/edit?usp=drive_web&ouid=111380676842996903308) SoftServ and British Libraries are slated to discuss the recommendation.

**Comment by jeremyf** [comment]
Given that @cziaarm has SharePoint working in BrowseEverything for another client, and there are no community suggested replacements, we're going to proceed with BrowseEverything as our intended technical delivery of @j-basford's stated functional needs.
