### ISSUE TITLE
Tenant security issue: Update to Bulkrax 5.0.0

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#227]
# Summary
Graham and i were just testing adding a new person to our [tryit.iro.bl.uk](http://tryit.iro.bl.uk/) for ppl who are interested in having a play with the system or who need to have access to it to demo it to their internal teams for getting signoff on joining, etc.
we added a new person to that tenant but realised he can log into all the other tenants too - admittedly he can't edit or delete content on those BUT he can create a new importer, so could theoretically add content to another org's repository...
which we obvs don't want, as one of the aspects of the shared service is a confidence that their repositories are secure from each other as well as any malicious outsiders!
is this a known issue? Maybe addressed in new v of hyku?

# Accepted Criteria
- [x] tenant user should not be able to export other tenant's data
# Notes

**Comment by jeremyf** [comment]
In conversation with Rob, the expected behavior and one that conforms to current technical functionality is for `When I create an account on a tenant, that account can't create/edit content (directly or via importers) of other tenants.` to be the acceptance criteria.

**Comment by j-basford** [comment]
The current behaviour unfortunately allows someone to export content - which isn't great, what if there's restricted material in there.

**Comment by bkiahstroud** [comment]
This is something I'm actively looking into as part of an upcoming feature that touches permissions in Hyku **a lot**. However, I think some changes in Bulkrax may also be necessary

**Comment by jeremyf** [comment]
@j-basford moving forward with this, we'll want to begin clearing the current round of Client QA; because one of the items is upgrading Bulkrax to v4.4.0 (#211) which inter-relates with many of the XML parser things (now also in Client QA).

**Comment by jeremyf** [comment]
See this branch https://github.com/scientist-softserv/britishlibrary/tree/i227

**Comment by laritakr** [comment]
See https://github.com/scientist-softserv/britishlibrary/pull/256#issuecomment-1412823815 for testing details.

**Comment by jeremyf** [comment]
Picking up QA on this

**Comment by j-basford** [comment]
tested as per Jeremy's test above (different new user) - behaved as expected

**Comment by grahamjevon** [comment]
behaved as expected in production. New user created and assigned to bl-demo tenant. User can login to other tenants, but cannot see import/export sections. While user can see works and collections sections, user cannot add, edit, or see any works or collections.
