### ISSUE TITLE
ORCiD and ISNI logos not displayed correctly

### ISSUE THREAD

**Issue by grahamjevon** [scientist-softserv/britishlibrary#232]
In the public facing metadata record, the ORCiD logo should be green and the ISNI logo should be blue. This displays correctly for creators. But for contributors and editors, ORCiD logos unexpectedly appear grey and ISNI logos unexpectedly appear black. Witnessed in staging and bl-demo.

![Image](https://user-images.githubusercontent.com/51366817/208936121-41328ed9-0014-444e-9b29-2a50d67c4ff0.png)

**Comment by summer-cook** [comment]
Example for isni: https://bl.iro.bl.uk/concern/book_contributions/11fcfb62-e69c-4841-acdb-c18f12df18a3
(can't find example for orcid)

**Comment by grahamjevon** [comment]
Happy that the logos are now displayed correctly (when the data remains present).

I used the phrase "when the data remains present" because testing this reminded me of [ticket 176](https://github.com/scientist-softserv/britishlibrary/issues/176) where data from some metadata fields is disappearing (including ISNI fields for contributors and editors).

**Comment by grahamjevon** [comment]
Looks to be working in production
