### ISSUE TITLE
Edit Controlled list of Institutions after Black Country Export

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/britishlibrary#234]
Only after getting the Black Country export (see ticket higher up - assuming the institution will need to remain to stop works  erroring) Please remove the following from the institutions controlled list: 

- [x] 1. Tate
- [x] 2. Barts Health NHS Trust
- [x] 3. Black Country Health Libraries Consortium
- [x] 4. Birmingham and Solihull Mental Health NHS Foundation Trust
- [x] 5. Gloucestershire Hospitals NHS Foundation Trust
- [x] 6. Norfolk and Waveney Integrated Care System
- [x] 7. Somerset NHS Foundation Trust

https://github.com/scientist-softserv/britishlibrary/blob/530dc521fda07600bf165e887650fe7ecf71f26f/config/authorities/institution.yml#L45

We likely want to deactivate the terms (e.g. `active: false`) then verify in the UI that those options are not available when you create a new work.

# Testing Instructions

Create or edit a work. 
The options in the Institution section should no longer contain the following: 

- [ ] 1. Tate
- [ ] 2. Barts Health NHS Trust
- [ ] 3. Black Country Health Libraries Consortium
- [ ] 4. Birmingham and Solihull Mental Health NHS Foundation Trust
- [ ] 5. Gloucestershire Hospitals NHS Foundation Trust
- [ ] 6. Norfolk and Waveney Integrated Care System
- [ ] 7. Somerset NHS Foundation Trust

# Notes
This list is in the edit form

**Comment by jillpe** [comment]
Blocked until we get a successful export

**Comment by cziaarm** [comment]
Update: Export is waiting for client verification

**Comment by j-basford** [comment]
For @j-basford to look at

**Comment by j-basford** [comment]
downloaded, no longer blocked

**Comment by jillpe** [comment]
SoftServ QA: PASS

<details><summary>Adding new work</summary>
Institution options only contain:
- British Library
- British Museum
- MOLA
- National Museums Scotland
- Royal Botanic Gardens, Kew
- National Trust

https://user-images.githubusercontent.com/84697174/229882597-a0f18f59-36b9-4a85-a159-454aafa93956.mov
</details>

<details><summary>Editing a work</summary>
[Work used](https://mola.bl-staging.notch8.cloud/concern/articles/fc16d327-ac97-4383-a17a-9d472d917545?locale=en)
Institution options only contain:
- British Library
- British Museum
- MOLA
- National Museums Scotland
- Royal Botanic Gardens, Kew
- National Trust

https://user-images.githubusercontent.com/84697174/229883348-ad3e7e79-7dc8-4b37-880f-6ec4284f1c52.mov

</details>

**Comment by grahamjevon** [comment]
BL QA: PASS

- Adding new work
- Editing new work

As expected, the list of institutions only includes the 6 live partners: BL, BM, Kew, MOLA, NMS, NT.
