### ISSUE TITLE
British Library Deploy Document for 2023-01 W2

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#244]
As of <span class="timestamp-wrapper"><span class="timestamp">&lt;2023-01-11 Wed&gt; </span></span> the current state of staging is broken (SHA `cfdbee67`).  As of <span class="timestamp-wrapper"><span class="timestamp">&lt;2023-01-11 Wed&gt; </span></span> the current state of production is SHA `6fa85515`.  

What we want to do is:

1.  Create a branch that builds from the last known good state
2.  Deploy that branch to staging
3.  Seek client verification
4.  Deploy that branch to production

****Building the a Functional Branch for Deploy****

At the bottom of this deploy document is a list of non-merge commits that are not in production.  It is generated by via the following `git slog 6fa8551.. --no-merges` (where `git slog` is a short log).

Given the broken state of staging, we want to first restore staging to a known “good state”.  That state is `6fa85515` (e.g. production’s current state).

From that good state we will create a branch.  Then cherry-pick commits that meet the following criteria:

1.  Added by April Rieger; these commits are related to infrastructure changes and do not have client oriented tests/nor issues.
2.  Pick all commits associated with tickets in the “Deploy to Production” column of the [britishlibrary Github project](https://github.com/orgs/scientist-softserv/projects/5/views/1).

With what remains, we’ll need to assess whether we add those commits or not; with an eye towards not including commits that are related to Bulkrax importers as those are the present broken state of staging.

In the below list, those with [x] indicates I’m planning to cherry-pick that commit into a `deploy-branch-for-2023-01-W2` branch.  Those without will be excluded.

-   [X] 5a9800d4 — remove fcrepo from default namespace, add it to fcrepo namespace. configure s3 access Rob Kaufman, (2023-01-17)
-   [X] c3f14d69 — updates the fcrepo host values to fcrepo.fcrepo.svc.cluster.local April Rieger, (2023-01-12)
-   [X] 845471ed — add national trust to list of institutions DeonFranklin, (2023-01-03)
-   [X] b19c2c03 — removed css to fix logos DeonFranklin, (2023-01-03)
-   [X] 92190c36 — updating the gha to v006 April Rieger, (2022-12-21) (origin/i512-update-gha-to-v006)
-   [X] 3b3b29f0 — added logo to shared theme DeonFranklin, (2022-12-20)
-   [X] 9253f1a0 — revert commit <https://github.com/scientist-softserv/britishlibrary/commit/ebcb8d59d2cc46ab2fa05431d0346c2707319d49> April Rieger, (2022-12-20)
-   [ ] c3d9647e — updated bulkrax from 3.5 to 4.4.0 DeonFranklin, (2022-12-19)
-   [X] a9ce8e8b — refactor April Rieger, (2022-12-13) (origin/v3plus5-deploy)
-   [X] 6de11de7 — update the deploy to have v3plus5 features in stand-alone April Rieger, (2022-12-13)
-   [X] ebcb8d59 — Switching to POST requests for SOLR Jeremy Friesen, (2022-12-15)
-   [X] 31cafec0 — Updated footer link to sotware services DeonFranklin, (2022-12-12)
-   [ ] 28e6a09b — cops fixes. remove accidentally committed file. added position counter that got missed. braydonjustice, (2022-12-13)
-   [ ] f1ea8099 — support for properly parsed names. braydonjustice, (2022-12-13)
-   [ ] 29948f91 — remove byebug braydonjustice, (2022-12-09)
-   [ ] 3c2dad12 — better refined type check for complicated elements braydonjustice, (2022-12-09)
-   [ ] 97325ebf — parser works but needs to deal with weird exceptions to the mapping (names need to be parsed etc) braydonjustice, (2022-12-09)
-   [ ] ae441f96 — initial setup for xml parser braydonjustice, (2022-12-07)
-   [X] 36db6bd9 — update lint and test to v3plus5 April Rieger, (2022-12-12) (origin/v3plus5)
-   [X] 41876025 — old actions repo branch chmod-backport April Rieger, (2022-12-12)
-   [X] 9638839c — make test and lint v3plus5 as well April Rieger, (2022-12-12)
-   [X] 79344b2a — syntax April Rieger, (2022-12-12)
-   [X] 17024b52 — update to branch v3plus5 github runners April Rieger, (2022-12-12)
-   [X] 0abf981b — make it dependent on the web AND worker amd64 builds to complete April Rieger, (2022-12-09)
-   [X] 78bcbeba — Favoring gem for graph indexing Jeremy Friesen, (2022-12-09)
-   [X] 6a212d1d — Update index.html.erb Deon The Dev, (2022-12-09)
-   [X] 75adb170 — Update bl-overrides.scss Deon The Dev, (2022-12-09)
-   [X] 9b36ac11 — fixed padding to align page DeonFranklin, (2022-12-08)
-   [X] 95383d10 — added banner image for the shared research repo DeonFranklin, (2022-12-07)
-   [X] 67be294d — Bumping Bulkrax to 3.5.1 Jeremy Friesen, (2022-12-01)
-   [X] 2dd67d23 — remove option worker true as it is not an input of this version April Rieger, (2022-12-06) (origin/arm-wrestle)
-   [X] 4c99e416 — re-run please April Rieger, (2022-12-06)
-   [X] 64e53156 — updates to the backport to add chmod April Rieger, (2022-12-06)
-   [X] e9c4f263 — needs the updated chmod in tests and lint on main which is also on arm-wrestle branch April Rieger, (2022-12-06)
-   [X] 273c7449 — updates actions to arm-wrestle branch April Rieger, (2022-12-06)
-   [X] 3cb62c66 — fixed linting error DeonFranklin, (2022-12-06)
-   [X] 8ceb5396 — Collaborative doctoral student has been added as a third category to the creator, contributor and editor institutional relationships DeonFranklin, (2022-12-05)
-   [X] 1fbee71d — Conditionally render BrowseEverything based on config Jeremy Friesen, (2022-11-30) (origin/jeremyf&#x2014;190)
-   [X] da1b77e7 — Move SOLR from Bitnami to address M1 chip issue Jeremy Friesen, (2022-11-30)

**Comment by jeremyf** [comment]
With this current round of QA, we can close this out because we have the Bulkrax upgrades in place.
