### ISSUE TITLE
Bulkrax timeout

### ISSUE THREAD

**Issue by grahamjevon** [scientist-softserv/britishlibrary#247]
A colleague was uploading[ a single work](https://bl.iro.bl.uk/concern/datasets/cf778baa-be01-4fe1-ae4d-4d3ef3fccf05) to bl.iro.bl.uk using bulkrax, when a timeout error interrupted the upload.

- They are using the csv with file urls method.
- The csv contains only one row. We advised she import one work at a time because of the size of the other files. I cannot attach a csv here so I will attach it to the [slack thread](https://assaydepot.slack.com/archives/G0313NK2LJ0/p1673957037926819?thread_ts=1673901115.373979&cid=G0313NK2LJ0).
- They are attempting to upload 15 zip files (each with its own url). The zip files are stored in Azure. Each zip file is approx 100-110MB.
- They tested this method several times on bl-demo.iro.bl.uk successfully before Christmas (though they did not test this exact work).
- Several of the files uploaded successfully on bl.iro.bl.uk yesterday, until they received the following error message: 

![Image](https://user-images.githubusercontent.com/51366817/212890748-8cee8b00-7e6e-4d20-bc31-2cfef17272dd.png)

**Comment by jeremyf** [comment]
I did some further digging, and the timeout issue is almost certainly related to a partial Fedora outage on Jan 16th; one of the nodes was down.  When we learned of it, we set about bringing that node back online (along with the others).

**Comment by jeremyf** [comment]
Given that this has now been experience twice, once during the above mentioned outage and another time, we need to explore duplicating the conditions of this importer in a suitable ecosystem and time so as to not disrupt working hour operations.

In addition to the above context we have https://assaydepot.slack.com/archives/G0313NK2LJ0/p1674141556225069

In our 2023-01-20 stand-up we were wondering if we need to look at the Fedora AWS configuration to tune it's memory and processor allocation.

**Comment by ShanaLMoore** [comment]
May  be a dev ops issue. @jillpe to reach out to @crisr15 to determine who will work on this.

**Comment by j-basford** [comment]
Thanks for the update on this via Slack, Rob - I'm guessing we can now move this to closed and keep an eye on how things go?
