### ISSUE TITLE
XML importer for UKETD_DC (EThOS content) to be labelled UKETD_DC

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#268]
![Image](https://user-images.githubusercontent.com/117307899/216088122-fa1a7d74-9d51-4543-a39b-0279531aee35.JPG)

In dropdown list for 'Parser' in import screen, the option is 'XML - ETD DC Parser'.

Please can it be amended to 'XML - UKETD_DC Parser'.

Reason: Unfortunately there is a UK and US version of ETD_DC, the American one is ETD_DC and the British one is UKETD_DC. EThOS is very specifically using UKETD_DC, so please could we have the label renamed accordingly? 

(This should be helpful as one day the US ETD parser might be in Hyku/Hyrax- they're not hugely different)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://britishmuseum.bl-staging.notch8.cloud/importers/new?locale=en

<details><summary>We renamed "XML - ETD DC Parser" to " XML - UKETD DC Parser"</summary>

![Screenshot 2023-03-08 at 12 25 06 PM 2023-03-08 at 12 26 00 PM](https://user-images.githubusercontent.com/29311858/223843509-272510a1-93e7-4eb1-b2b9-8ce550274d4f.jpg)</details>

**Comment by j-basford** [comment]
passes qa
