### ISSUE TITLE
XML parser: no ResourceType being selected (should be ThesisOrDissertation --> Thesis)

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#269]
Currently no RT is being displayed on public end, or selected in edit screen for XML content.
If using a parser for UKETD_DC then it can be assumed that it will only be Work type: ThesisOrDissertation and Resource type: Thesis (no masters dissertations in EThOS)

![Image](https://user-images.githubusercontent.com/117307899/216099912-d4b581b0-b05f-4e74-a9a2-d6ebc19a31a2.JPG)

# Testing Instructions

- [ ] Login as an admin
- [ ] Navigate to the Works link in the sidebar
- [ ] Click add new work
- [ ] Select Thesis or Dissertation and create work
- [ ] Fill in required sections
- [ ] For resource type select Doctoral Thesis
- [ ] For Qualification name select PhD

Once the work is created, verify the resource type shows up above the title.

**Comment by jillpe** [comment]
Related to #270 - suggested to complete both at the same time

**Comment by DeonFranklin** [comment]
--Testing Instructions

- [ ] Login as an admin
- [ ] Navigate to the Works link in the sidebar
- [ ] Click add new work
- [ ] Select Thesis or Dissertation and create work
- [ ] Fill in required sections
- [ ] For resource type select Doctoral Thesis
- [ ] For Qualification name select PhD

Once the work is created, verify the resource type shows up above the title.
