### ISSUE TITLE
XML parser for UKETD_DC does not handle Qualification Name

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#270]
For ThesisOrDissertation, there is a mandatory field in our schema: 'Qualification name'

Qualification name is currently showing - 'Thesis (Ph.D.)' in the public end.
See screenshot: 

![Image](https://user-images.githubusercontent.com/117307899/216101599-1548e06e-33b1-41ef-ac68-c221d73495b1.JPG)

Qualification name should really show like this, i.e just 'PhD' and 'Thesis' should not be in there - it should conform to a dropdown list:

![Image](https://user-images.githubusercontent.com/117307899/216101856-8701f1f9-841c-497b-896f-b2c7f6b86c76.JPG)

I don't know if qualification level shows in the XML? we can map it if so to each of the dropdown list?

# Testing Instructions

- [ ] Login as an admin
- [ ] Navigate to the Works link in the sidebar
- [ ] Click add new work
- [ ] Select Thesis or Dissertation and create work
- [ ] Fill in required sections
- [ ] For resource type select Doctoral Thesis
- [ ] For Qualification name select PhD

Once the work is created, verify PhD shows correctly as the qualification name in the metadata.

**Comment by jillpe** [comment]
Related to #269 - suggested to complete both at the same time

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://mola.bl-staging.notch8.cloud/concern/thesis_or_dissertations/887f78a1-cb5a-4434-a9d8-a147684c1422?locale=en

<details><summary>The metadata "Qualification name: select PhD" appears on the work show page</summary>

![Thesis Or Dissertation 2023-04-18 7 tasks XML parser no ResourceType being selected (should be ThesisOrDissertation -- Thesis) ID 887f78a1-cb5a-4434-a9d8-a147684c1422 Hyku 2023-04-18 at 3 45 24 PM](https://user-images.githubusercontent.com/29311858/232921634-700aee11-25b1-40e1-acd3-f4af15c42ee7.jpg)
</details>
