### ISSUE TITLE
Error with CSV Importing

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/britishlibrary#275]
# Summary 

> since last night's deploy we have been getting bulxrax csv import errors. Always the same error: `Error: IndexError - string not matched`. I have tried this on a csv that imported successfully on bl-demo last night, but which fails today. Our standard testing template which we regularly import for testing has is also failing today with the same error.

(See https://assaydepot.slack.com/archives/C0313NK2LJ0/p1675946383097809)

Problem experienced with the following importers:

- https://bl.iro.bl.uk/importers/87?locale=en 
- https://bl-demo.iro.bl.uk/importers/144?locale=en
- https://bl-demo.iro.bl.uk/importers/143?locale=en

The `adding-spec-to-prove-bug` branch has a spec that demonstrates the problem.

# Acceptance Criteria

- [x] Creating a bulkrax import w the sample file (below), should be successful. It should not error out with `Error: IndexError - string not matched`.

# Screenshots or Video

# Testing Instructions

Import the following sample file: [british-library.csv](https://github.com/scientist-softserv/britishlibrary/files/10736100/british-library.csv)

# Notes

**Comment by ShanaLMoore** [comment]
Our proposal is to update the CSV header to current_he_institution_name. We will then update Bulkrax.rb field mappings to be 'current_he_institution_name' => { from: ['current_he_institution'], object: 'current_he_institution' }

The above suggestion successfully imports the work and breaks current_he_institution down to a complex object, which looks something like ...


```
book.current_he_institution => {
  current_he_institution_name => "",
}
```

If not, we will need to solve a much harder bug. cc @jeremyf @kirkkwang

**Comment by ShanaLMoore** [comment]
The client is ok with updating their CSV's header, but the request is to give them an updated CSV example. 

cc @jeremyf

**Comment by DeonFranklin** [comment]
This ticket passes Soft Serve QA. See attached screenshot:

**Comment by grahamjevon** [comment]
The standard BL test csv template successfully imported with current_he_institution_name as the column header instead of current_he_institution. Also successfully imported a BM csv.

**Comment by jeremyf** [comment]
@NoraRamsey

**Comment by NoraRamsey** [comment]
Importer works successfully with current_he_institution_name filled in and also when left blank.
