### ISSUE TITLE
Bulkrax schema migrations are missing from the application

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/britishlibrary#277]
### Descriptive summary

The Bulkrax schema migrations are missing from the application.  The result is two fold:

1. We are missing expected database columns.
2. We cannot smoothly install new migrations.

The underlying problem is as follows:

```
PG::UndefinedColumn: ERROR:  column bulkrax_pending_relationships.importer_run_id does not exist
LINE 1: ...nt_id" FROM "bulkrax_pending_relationships" WHERE "bulkrax_p...
                                                             ^
: SELECT "bulkrax_pending_relationships"."parent_id" FROM "bulkrax_pending_relationships" WHERE "bulkrax_pending_relationships"."importer_run_id" = $1
```

[See exception][1]

We are expecting a column named `importer_run_id` but according to [our schema][2] we have have `bulkrax_importer_run_id`.  Digging a little further, it appears that we don't have any migrations loaded for Bulkrax.  Those were instead added directly the the `db/schema.rb`.

### Background

It is customary when including an engine to install the migrations (e.g. `rake bulkrax:install:migrations`).  This copies the migrations from the engine into the application; further it allows us to run the same command later and get any new migrations.

See https://guides.rubyonrails.org/engines.html#engine-setup for more details

### To Resolve

Fundamentally, we need [this migration from Bulkrax][3].  However, if I run `rake bulkrax:install:migrations` that adds all of the engine migrations to the application.  We can't add those migrations without review; because those migrations would run on-top of the existing migrations and might drop (and then re-add) database columns.

Our ideal state is for us to get to a point where we can run `rake bulkrax:install:migrations` in the future and it will add any new migrations that we don't have.

However, to get there, we'll need to explore how to tell our application that we have those migrations.

[1]: https://scientist-inc.sentry.io/issues/3885033477/?project=6745017&query=is%3Aunresolved&referrer=issue-stream

[2]: https://github.com/scientist-softserv/britishlibrary/blob/1e22d5071d0de31255c3df4a22fdd1607c886794/db/schema.rb#L148-L156

[3]: https://github.com/scientist-softserv/britishlibrary/blob/1e22d5071d0de31255c3df4a22fdd1607c886794/db/migrate/20220609001128_rename_bulkrax_importer_run_to_importer_run.rb#L1

**Comment by alishaevn** [comment]
in addition to running new migrations, old migrations would need to be removed.

how we handle pending relationships has changed over time which may be how you're getting the error above in the first place.

**Comment by jeremyf** [comment]
> in addition to running new migrations, old migrations would need to be removed.

I'm confused.  I'm not accustomed to removing migrations from Rails applications.  Typically, migrations are run, registered in the database, and then forever ignored.

> how we handle pending relationships has changed over time which may be how you're getting the error above in the first place.

I definitely assume as much.  I'm not seeing a clear pathway on how to do this, because our `db-migrate-seed.sh` script looks **very** aggressive (e.g. perhaps only run it once?)

**Comment by alishaevn** [comment]
> I'm confused. I'm not accustomed to removing migrations from Rails applications. 
as I think about that more...you're right. I was thinking about how a table/column name may be changed, but a new migration would just be created for that adjustment. so no deleting migrations.

>  our db-migrate-seed.sh script looks very aggressive
I don't fully understand that file so I'll leave that to someone else.

**Comment by ShanaLMoore** [comment]
TODO: in BL's server, try running rake db:migrate:status

**Comment by ShanaLMoore** [comment]
migrations ran and successfully completed, in r2-bl/hyku-production-hyrax

ref: https://assaydepot.slack.com/archives/G0313NK5NMA/p1676407875637269
