### ISSUE TITLE
Spike: Large Zips Downloaded via Remote Fetch are not working

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/britishlibrary#283]
## Problem Statement

> Each csv contains only one row of metadata for one single work. The files that accompany that work are large. In this instance she is attempting to upload 6 zip files. These zip files are stored in Azure. And she is uploading them using the BX url method (pointing to the azure url) rather than the BX zip method. Here is [an example of what a successful upload should look like](https://bl.iro.bl.uk/concern/datasets/f4761b24-54b6-413c-8acb-92cef09866fb).

## Preliminaries

What we don’t know is how unzipping, in the current implementation, affects memory.  It is easy to see a case where unzipping 10 GB requires 10 GB of memory.

It is also possible that it’s not being written to a mounted volume (which has the space) but instead to the machine’s storage (which doesn’t have the space).

## Goal

To understand why the file size is creating problems.  This is a size we should be able to handle.

**Comment by kirkkwang** [comment]
The tmp directory was getting filled and evicting the worker containers.  Rob is going to experiment with giving it more storage (250 gigs worth) but that requires a Kubernetes upgrade from 1.20 to 1.23 which will take a day or two.

**Comment by kirkkwang** [comment]
https://assaydepot.slack.com/archives/G030UPFBT2S/p1678123793641269

From Rob:
> I’ve started a PR that puts the tmp space in /app/samvera/hyrax-webapp/tmp/shared. We need to change where the process uses for tmp during download so that it writes them here instead of the main tmp.  This is not the ephemeral storage thing, but we could use that later if we decide its a better fit. It uses the efs instead since we haven’t been able to complete the upgrade. That will be slightly slower, but it will work
