### ISSUE TITLE
ISNI being lost from contributor and editor

### ISSUE THREAD

**Issue by cziaarm** [scientist-softserv/britishlibrary#300]
from #176 

Something similar is happening with the following fields:

Contributor > ISNI
Editor > ISNI
User Story:

1> Select "Add New Work"
2> Enter metadata, including the two fields above
3> Save record
4> Public facing metadata record shows this data as expected
5> Select "Edit" work
6> The two fields above will be empty
7> If you save this record (e.g. because you want to edit another field), the ISNI data will be lost.

**Comment by grahamjevon** [comment]
Passes BL QA. ISNI data saved and stored successfully in creator, contributor, and editor fields (for both personal and organisational types). Tested on 3 work types: Book Contribution, Article, Image.
