### ISSUE TITLE
Configure iiif in BL

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#303]
# Summary

Once IiifPrint is installed, we should communicate with the client to clarify which configurable features to enable. 

Give the client the options or review their SOW (look in google drive or ask Jill), and update this ticket with what needs to be done.

# Configuration Options ([see later comments](https://github.com/scientist-softserv/britishlibrary/issues/303#issuecomment-1468507060))
- [x] 

# Testing Instructions

- [ ] All work types should split attached PDFs into individual works of the same type, with one attached jpg per page.
- [ ] All work types should create text derivatives on attached files
- [ ] child works should not show in search results
- [ ] works should be text searchable, with the parent work returned in the search
- [ ] Button to open in universal viewer should show for works with image, video, or audio files attached directly or via child works
- [ ] Universal viewer option should not show for works without valid file type attachments. 
- [ ] Text should be searchable in universal viewer with pages highlighted

# Notes

Client may want to hide the child works in the parent work's items section

**Comment by ShanaLMoore** [comment]
TODO: prepare q's to ask in their client iteration mtg tomorrow

**Comment by ShanaLMoore** [comment]
client agreed to go with iiif_print but with png derivatives, instead of tiffs

**Comment by jillpe** [comment]
Configuration Updates per 2023-03-14 meeting:

**PDF Splitting**
- Prefer the lower power/storage formats (JPG, txt)

**Derivative Types**
- Again, prefer the lower power/storage formats (No TIFFS or PDFs)

**Catalog Search**
- Confirmed they only want parents (NO children) to return in the search
- Need to make sure children do not return in the recent additions feed as well

**Comment by laritakr** [comment]
Note: children do not appear in the recent additions feed but they DO appear in recent works on the home page. 

**Recent Additions:**
![Screenshot 2023-03-15 at 6 27 26 PM](https://user-images.githubusercontent.com/17851674/225457567-0dbafb55-ea1f-4a93-8fcb-d9b4ae7f7cf3.png)

**Home page**
![Screenshot 2023-03-15 at 6 27 32 PM](https://user-images.githubusercontent.com/17851674/225457578-55cf5e09-f14e-42c1-8db6-793da6be0e67.png)

**Comment by DeonFranklin** [comment]
PDF Split
![Image](https://user-images.githubusercontent.com/95306716/225736926-92e61948-1e7b-4495-9db1-3d70f07a3760.png)

Search showing parent work only
![Image](https://user-images.githubusercontent.com/95306716/225737248-ccdb24af-accd-43e0-97b7-844eec281327.png)


Button to open in universal viewer
![Image](https://user-images.githubusercontent.com/95306716/225737615-0c602541-411a-4da7-a35b-d39baa06afb6.png)


Search in viewer
![Image](https://user-images.githubusercontent.com/95306716/225733857-f50144e3-3c82-46ae-b43c-52058163d428.png)

**Comment by jillpe** [comment]
BL QA Findings: https://assaydepot.slack.com/archives/C0313NK2LJ0/p1681316986158039

**Comment by ShanaLMoore** [comment]
# QA RESULTS (to address client concerns)

## Issue 1
I added [a work](https://bl.bl-staging.notch8.cloud/concern/books/0d00db38-1339-48df-851a-920017de69a4) via UI and attached 2 pdf files
As expected it split the works into jpg files as child works
As expected, I can click a jpg child and within that record I can open that single jpg in the UV successfully.
- [ ] ISSUE: However, if I try to open the full parent record in the UV, the the UV does not load. I just see a black screen.

## Issue 2
I added [a work](https://bl.bl-staging.notch8.cloud/concern/books/442694a5-d0af-4340-b7da-398c4fa566a3?locale=en) via UI, but did not attach any files
I edited the work, uploaded a single pdf, and clicked save
- [ ] ISSUE: This pdf failed to save. The record says it has no files attached. If I go to edit the record again, there is no sign of the previously uploaded file.
  - I have just replicated this issue by uploading a file at the point of adding [another work](https://bl.bl-staging.notch8.cloud/concern/books/03d3586e-52a2-4d87-9ee0-cfea5d85fed3?locale=en). I wonder if there is a blockage in sidekiq?

**Comment by grahamjevon** [comment]
@ShanaLMoore I agree that the two specific issues you re-tested also pass BL QA. I haven't yet tested iiif print in full. Two quick observations I just noticed:

1. the word search in the UV seems to work better on individual words rather than phrases. For example, if I search for the name "Gertrude Bell" in [this file](https://bl.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://bl.bl-staging.notch8.cloud/concern/articles/c5dd3830-8c80-4677-a0b7-3eab09db2d3d/manifest&config=https://bl.bl-staging.notch8.cloud/uv/uv-config.json), it only highlights "Gertrude". It doesn't highlight "Bell". But if I search for "Bell" as an individual word, it does find that surname.

3. There is now a mismatch in how pdfs are listed as items in the metadata record and how they are displayed in the UV. For example, in [this work](https://bl.bl-staging.notch8.cloud/concern/reports/1bf34fe6-601d-4d04-a808-b61db482d289?locale=en), 

![Image](https://user-images.githubusercontent.com/51366817/233163286-35a0ece4-a6a2-4266-a9b8-2ae497e362b0.png)

![Image](https://user-images.githubusercontent.com/51366817/233163434-c298a677-9809-45c4-9295-bed0d18ee2a2.png)

**Comment by ShanaLMoore** [comment]
@grahamjevon 

1) That is correct, we are aware that there are current limitations to searching for multi-words/sentences. I wouldn't consider that a bug at this time. 

2) For iiif-print there will be ways to customize sort orders. I will close this ticket since this point is out of scope for the concern of the immediate issue. But I will pull in cc @kirkkwang and @laritakr for better guidance here, and we'll create a separate ticket if  necessary.

**Comment by laritakr** [comment]
Recent changes to ensure unique titles for the child works incorporated the PDF name into the title. This was necessary to resolve other bugs connecting the children to the parent work in cases where parent works may not be unique. 

These child works are then sorted alphabetically by title so they are in page number order within the PDF, and this is how they are shown in the UV. However the PDFs themselves are not sorted alphabetically, as they always appear in the order added unless this is manually adjusted via the UI.
