### ISSUE TITLE
Spike: Demo PDF viewing, v3 manifest for BL

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#305]
# Summary

Demo to make a decision for PDF viewing. Should we use iiif_print's PDF Splitting (because the client doesn't need OCR and implementing the PDF Splitting requires a lot more storage) or something else? Consider size and processing for computations. 

ref: https://github.com/scientist-softserv/britishlibrary/issues/193

OPTIONS
- [ ] PDF manifest (better storage and import, but no uv search feature)
- [ ] PDF Splitting with tiffs (natively comes w iiif_print, will cost a lot more in terms of storage per PDF)
- [x] PDF Splitting with PNG instead (since they are a lot smaller)
  - NOTE: PNGs (or any other format) may see some slight performance issues vs delivering pyramidal TIFFs, though this has not been measured by us to see how big of the impact will actually be in production
  - we can make this [configurable](https://github.com/scientist-softserv/iiif_print/blob/bda193c6dd4d17d9769946decb7adbc30037745c/lib/iiif_print/split_pdfs/pages_into_images_service.rb#L102-L115) or make it a specific override for BL. 

# Acceptance Criteria

- [ ] Give client a hand full or options, pros/cons and demos for PDF viewing. Give a recommendation. Have the client approve one of them. Update implementation [ticket](https://github.com/scientist-softserv/britishlibrary/issues/193) with the winning option.

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
@jillpe we are recommending the third option. Will you discuss this with the client to confirm? cc @kirkkwang

**Comment by kirkkwang** [comment]
## PDF manifest

### Pro:
- better storage and import

### Con:
- no uv search feature

### Steps to get there
- needs some work for PDF manifest generation through the IIIF Manifest gem

## PDF Splitting with tiffs

### Pro:
- can OCR pages and store results for searching (catalog search and UV search)
- can search for child metadata through UV

### Con:
- will cost a lot more in terms of storage per PDF

### Steps to get there
- IIIF Print already does this, we just need to install it

NOTE: each page becomes its own work and has metadata

## PDF Splitting with PNG instead

### Pro:
- PNGs are much smaller than TIFFs and won't cost as much in storage

### Con:
- there might be slight performance issues for larger resolution images

### Steps to get there:
- Override existing TIFF generation with PNG generation in IIIF Print gem

Our recommendation is **PDF Splitting with PNG instead**

**Comment by ShanaLMoore** [comment]
The client has decided to go with the iiif_print + png option. We will create a ticket and close this spike.

**Comment by ShanaLMoore** [comment]
https://github.com/scientist-softserv/britishlibrary/issues/314
