### ISSUE TITLE
Add persistent volume for the `/tmp` directory

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/britishlibrary#307]
ref #283 

# Summary

Importing the below csv only ends up with one successful import because the volume runs out of memory and evicts the worker pod.

# Acceptance Criteria

- [x] A tmp/shared directory is created

**Comment by ShanaLMoore** [comment]
Per the BL iteration meeting, the client agreed that we can pull this one into our next sprint.

**Comment by kirkkwang** [comment]
The new dir was added with larger storage limits but the initial issue was not solved, spun off to #392 and closing this ticket
