### ISSUE TITLE
Spike: Is there a way to make the difference between files and works clear

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#325]
# Summary
Per client meeting 2023-03-14 - client wants a way to make difference between the file sets and child works clear. 

Suggestion of Jeremy:
- [ ] #339
- [ ] Feature 2: Clearly mark file sets as split pages
- [ ] Feature 3: (Not requested) Provide filtering to show only split pages or not split pages.

# Accepted Criteria
- [ ] A path forward is clearly defined and outlined in follow up tickets

**Comment by ShanaLMoore** [comment]
Scenario: 

When a user imports a parent work with a PDF and children, in the items section where children and files are displayed, the files should be displayed first (at the top)
