### ISSUE TITLE
Address spec failures: BL

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#326]
# Summary

I updated UTK's github workflow to pull in a bug fix found in gh actions. The pipeline should fail when specs do. However in doing so, it exposed 3 spec failures. 

ref: https://github.com/scientist-softserv/utk-hyku/pull/366

failure ref: https://github.com/scientist-softserv/britishlibrary/actions/runs/4418103474/jobs/7745605115

![Image](https://user-images.githubusercontent.com/10081604/225138783-34cb04ff-0df8-4603-8281-a61c6ac1afa2.png)

## Presently failing specs:

- ./spec/features/create_image_spec.rb:75
- ./spec/features/create_generic_work_spec.rb:78
- ./spec/features/appearance_theme_spec.rb:58
- ./spec/features/appearance_theme_spec.rb:40
- ./spec/features/appearance_theme_spec.rb:152
- ./spec/features/appearance_theme_spec.rb:127
- ./spec/features/appearance_theme_spec.rb:77

**Comment by ShanaLMoore** [comment]
The issue with both tests seems to be caused by a method called #find_children_of. 



![Image](https://user-images.githubusercontent.com/10081604/225141792-3c96cc9d-01b9-4771-9f74-955a823c5282.png)

Instead of using the method defined in [hyrax v2.9.6](https://github.com/samvera/hyrax/blob/v2.9.6/app/models/concerns/hyrax/collection_nesting.rb#L45-L47), it's using one defined by the v2_graph_indexer.rb which simply returns true. So when we iterate over the returned valued, it breaks and causes the specs to fail. 



![Image](https://user-images.githubusercontent.com/10081604/225142200-f9e45687-d71c-4687-b125-581a8ca2c02b.png)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://github.com/scientist-softserv/britishlibrary

<details><summary> Pipeline is green</summary>

![scientist-softservbritishlibrary 2023-03-27 at 2 46 01 PM](https://user-images.githubusercontent.com/29311858/228080117-641765b7-3d9a-4bd5-bf1a-0f54a7f0f5b7.jpg)</details>

**Comment by DiemBTran** [comment]
Closing because this was an internal issue
