### ISSUE TITLE
Feature 1: We should sort by putting original files at top and constituents below

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#339]
# Summary

When a user imports a parent work with a PDF and children, in the items section where children and files are displayed, the original files should be displayed first (at the top)

# TESTING INSTRUCTIONS

- [ ] Create a work that has mixed file types (jpg and pdf). 
- [ ] Uploading a PDF should split and create child works. 
- [ ] Confirm that the file types (aka original files) should display at the top of the items section, before the child works.

**Comment by laritakr** [comment]
The show page is currently ordered by: 

- Original files attached to the work as it was created.
- All child works split from original PDFs during the initial ingest, sorted by PDF number & page number.
- Additional original files attached to the work via edit.
- Additional child works split from a PDF via an edited work, sorted by PDF number (starting again with 1) & page number.

Sequence can be modified using the "File Manager" button on the work's show page. 

Note that all PDF files must currently be added at once to avoid duplicate titles during PDF splitting. We currently do not support adding PDF files to a work at separate times.

**Comment by ShanaLMoore** [comment]
cc @laritakr Could you add testing instructions to this one please?

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

- [ ] I created a [work](https://mola.bl-staging.notch8.cloud/concern/generic_works/24f9d384-efe0-4914-ac95-70dccc742e2c?locale=en) with a jpg and a multi page pdf file

JPG: ![Image](https://user-images.githubusercontent.com/10081604/232632778-8cb056ba-982b-4791-8ca2-4fa01f068d80.jpg)
PDF: [iiif-print-test.pdf](https://github.com/scientist-softserv/britishlibrary/files/11256543/iiif-print-test.pdf)



- [ ] The "original files" (jpg and PDF) were at the top of the items section. The PDF split created child works, but the original files were sorted correctly. 



![Image](https://user-images.githubusercontent.com/10081604/232632829-bbe5ef35-e32e-4b37-a6a8-db65ff6d4e7b.png)

**Comment by jillpe** [comment]
@ShanaLMoore yes we got feedback in our meeting on 2023-03-28:

>  Ideally, the client would want the cat_scan pdf to be towards the top. We discussed, due to possible scope creep, Rory and BL will discuss possible options for a better solution in the future (such as hiding the child works from the items section. Doing so would remove the ability for a user to click into the child work. Edit may have to be done via bulkrax, or we could consider adding a link in the manifest. Or the child works can only be visible to a certain user type, in the items section). For now, the client may have to manually change orders using the File Manager.
