### ISSUE TITLE
Creator, Contributor, and Editor should show up correctly

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/britishlibrary#345]
# Story

As a user, I should see creator, contributor, and editor metadata show up correctly in the metadata pane.

# Acceptance Criteria

- [ ] creator, contributor, and editor fields should show up as `family_name, given_name`

# Screenshots / Video

![Image](https://user-images.githubusercontent.com/19597776/226741179-d550eed0-0745-4256-90c0-32c89e2bf847.png)

# Testing Instructions and Sample Files

- [ ] Go to a work that has creator, contributor, and editor
- [ ] See that they show up correctly as `family_name, given_name`

# Notes

This should be a decorator for IIIF Print since it is a very specific BL problem

**Comment by kirkkwang** [comment]
ref branch `i345-configure-uv-metadata`

**Comment by ShanaLMoore** [comment]
# QA RESULTS: 

- [ ] Go to a work that has creator, contributor, and editor
  - [ ] See that they show up correctly as family_name, given_name

**Comment by ShanaLMoore** [comment]
The above problem seems to only relate to the bl tenant. We will pair with Rob to resolve, for now it may be best to not QA with the bl tenant, until further notice. 

![image](https://user-images.githubusercontent.com/10081604/232631979-dc9bd285-2e5e-4871-ad51-0d96520859ce.png)
