### ISSUE TITLE
Kew CSV exports 2023-03-31

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#353]
# Summary
our partners at Kew again need csv exports for their reporting to their board of trustees. As the exporters feature of the repository is still not working, please can you arrange for these to be generated? I believe that 
Rob had a method for nursing these a month or so ago when Kew last had this issue. Kew need Metadata exports by the following work types:

- Articles
- Books
- Book contributions
- Conferences
- Datasets
- Exhibitions
- Generic works
- Images
- Reports
- Theses/Dissertations

Kew need this before the end of this week. They have also asked if you can confirm the date/time of each report so that Anne can manually add any works that she uploads after the export was run. Ideally Kew would like the csv exports to be available by Friday morning (UK time), so that they have time to "crunch" the numbers during the day.

# Accepted Criteria
- [ ] Kew has csv exports before their BOD Friday for the above work types

# Notes
[Slack Thread](https://assaydepot.slack.com/archives/C0313NK2LJ0/p1676850755843149?thread_ts=1676635112.118209&cid=C0313NK2LJ0) that might be helpful 

[Code that might be helpful](https://gist.github.com/orangewolf/9819d778264d0c836bb716428e92d021)

**Comment by jillpe** [comment]
dependent on #289 and testing with a new tenant

**Comment by ShanaLMoore** [comment]
We will try to get code deployed to production first, to unblock Kew from generating their own reports.

**Comment by ShanaLMoore** [comment]
ref: https://assaydepot.slack.com/archives/C0313NK2LJ0/p1680061678641029

Per Jeremy "the production deploy is complete...
To recap, we took the code state of yesterday’s production and added in the Bulkrax updates.  We deployed that to staging, which you tested this morning.  I then deployed that same code to production.
We’re going to circle back to the other code that was once on staging."
