### ISSUE TITLE
Set env var `OMP_THREAD_LIMIT` to 1

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/britishlibrary#357]
# Story

Currently it is taking a very significant amount of time to process tesseract OCR in a deployed environment.

# Acceptance Criteria

- [ ] Tesseract should not take hours

# Notes

After adjusting the OMP_THREAD_LIMIT, close this ticket.

ref from ADL: https://github.com/search?q=repo%3Ascientist-softserv%2Fadventist-dl%20OMP_THREAD_LIMIT&type=code

**Comment by DiemBTran** [comment]
QA notes:

tested on:
- https://mola.bl-staging.notch8.cloud/concern/books/ce6df3af-bbac-4075-b571-05bff02ea6e8?locale=en
- work was created at 11:50am PT

**Comment by DiemBTran** [comment]
tested on:

- sample file 1: [service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf](https://github.com/scientist-softserv/britishlibrary/files/11103864/service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf)
- sample file 2: [sample.pdf](https://github.com/scientist-softserv/britishlibrary/files/11103866/sample.pdf)
- test 2: https://mola.bl-staging.notch8.cloud/concern/articles/0c12d382-26e9-4c69-9adf-dd4f1757ddd5?locale=en

Test 1 with sample 1, got this error:
`Ldp::HttpError: STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "da39a3ee5e6b4b0d3255bfef95601...`

Test 2 with sample 2, got this error:
`ActiveJob::DeserializationError: Error while trying to deserialize arguments:`

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- [sample (1).pdf](https://github.com/scientist-softserv/britishlibrary/files/11106925/sample.1.pdf)
- https://mola.bl-staging.notch8.cloud/concern/articles/5daee8a9-1255-4860-9ca9-3df916ddf993?locale=en
- https://bl-staging.notch8.cloud/sidekiq

<details><summary> This 2 page PDF completed all of its processes in under 5 minutes
</summary>

![Sidekiq 2023-03-29 at 6 32 37 PM](https://user-images.githubusercontent.com/29311858/228705119-fed96017-ea96-4dff-8df8-b89d187e972b.jpg)
</details>

**Comment by DiemBTran** [comment]
closing this ticket since it was an internal issue
