### ISSUE TITLE
Model Mismatch in Fedora

### ISSUE THREAD

**Issue by grahamjevon** [scientist-softserv/britishlibrary#368]
In tenant bl-demo.iro.bl.uk I created a [metadata only export for work type articles](https://bl-demo.iro.bl.uk/exporters/50?locale=en). This export unexpectedly included 8 works where the dataset is actually "Dataset".

![Image](https://user-images.githubusercontent.com/51366817/228779298-0b9e1a55-68e7-4aa5-b7a1-3b9e9a845e47.png)

In the search results field, when the work type facet is set to "Article", these works are also unexpectedly returned.

![Image](https://user-images.githubusercontent.com/51366817/228779114-d7d33d2d-64ed-485b-92de-45b5633c2310.png)

@ShanaLMoore observed: "The weird thing is. I'm in the rails console for production and when I try to find id c8712f00-8bfd-4f10-9054-1e5b90d63d64, it returns as an Article."

![Image](https://user-images.githubusercontent.com/51366817/228779241-1bd32502-bb02-4838-b4f1-80f96bbf14f7.png)

This bug(?) was identified at the same time as issue #369.

**Comment by cziaarm** [comment]
Hi @grahamjevon The exporter exported only Articles. The issue is that 8 of those Articles had the resource_type value set to Dataset (specifically "Dataset default Dataset"). The model is indeed an Article so the exporter is working as expected.

**Comment by grahamjevon** [comment]
Hi @cziaarm, what field in Hyku populates the "model" column in the exporter? I notice that the "model" column is not in the importer so I can't see the metadata mapping in the csv template. My assumption was that this corresponded to the "Work type" (particularly given that the terminology in the exporter is "Export From: Work Type" and "Work Type: Article". If that is all true, how would it be possible for a work to exist that has Work Type "Article", but resource type "Dataset Default Dataset"? My understanding of the "Dataset default Dataset" syntax is that the first "Dataset" in the phrase refers to the work type and the second "Dataset" in the phrase refers to the resource type. Also, when adding a work and "Article" is selected as Work type, my understanding is that it shouldn't be possible to select dataset as resource type. For these reasons, I am confused as to why these 8 datasets appear in the "Work type: article" export.

![image](https://user-images.githubusercontent.com/51366817/229447488-938ae45b-f1b8-4d3d-a4e2-ed2ad80d5ad2.png)

**Comment by ShanaLMoore** [comment]
This one is in Rory's court but just chiming in. 

I noticed that when I click edit on [c8712f00-8bfd-4f10-9054-1e5b90d63d64](https://bl-demo.iro.bl.uk/concern/articles/620f37a4-12f4-43a9-836d-3d6488e7e5a4/edit?locale=en#metadata) no resource type is selected and it's missing a few other required fields too. Via the UI, this work will not save without such required fields.

Usually this hints that the work was created via bulkrax, which doesn't go through the same validation process as the UI (ie: it will still create works even if certain values are missing or wrong). So it's possible that the csv responsible for this work was wrong. Resource types unavailable via the UI would still get processed and created via bulkrax, even if the csv listed otherwise.

**Comment by cziaarm** [comment]
Thanks @ShanaLMoore! @grahamjevon Shana's thinking matches mine, in that this looks like a record imported via Bulkrax.

When creating a record via the UI The first step is to select the "Type" from the select menu (the one before we even get to the form) under the hood what we are doing is selecting the _model_ that will inform the metadata profile and various behaviours. We generally then have the opportunity to select a sub-type this is the resource type. Via the UI your choice will be restricted to things that go with the model, so if you create an article you won't have the opportunity to set its Resource type to Dataset.

However when importing there is less opportunity for these checks and balances (other than those that the importer does themselves) and it is possible to end up with records like the ones in this case. 

Shana's course of action is also spot on. If this these are articles without a resource type then this can be set via the UI. If they are Datasets that have used the Article model then they will need to be re-created.

**Comment by grahamjevon** [comment]
Thanks @ShanaLMoore @cziaarm - that explains how it was possible to have such a mismatch of data.
