### ISSUE TITLE
BL prod/staging mismatch

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#376]
# Summary

The last time I checked, prod is several, many commits behind staging. This made it a little more difficult to resolve the hotfix issues we experienced last week. 

This ticket is to come up with a plan to clean up the discrepancies. Ideally we want to deploy main or something close to it. 

Deploy everything to main and ask client to QA

**Comment by ShanaLMoore** [comment]
TODO: 

Client needs to QA and approve the state of staging

**Comment by jillpe** [comment]
Verify everything in staging - please hold off on testing in production until this is resolved.

**Comment by ShanaLMoore** [comment]
We will deploy to prod once the client has finished approving all recent work.

**Comment by jillpe** [comment]
this is resolved
