### ISSUE TITLE
Arabic file import fails pdf splitting

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/britishlibrary#385]
# Story
Work: https://bl.bl-staging.notch8.cloud/concern/books/8beed1ee-e4ef-412e-92b3-8718ca8e3e10

The arabic file on this work is just sitting in sidekiq during the pdf split process and not doing anything. It appears to be locking up on `Open3.popen3(cmd) do |_stdin, stdout, _stderr, _wait_thr|` line. Is there a better way to open the pdf file and run the ghostscript command on it?

See also: 

- https://stackoverflow.com/questions/8952043/how-to-fix-hanging-popen3-in-ruby
- https://www.rubydoc.info/stdlib/open3/Open3.popen3

# Acceptance Criteria

- [ ] Identify reason arabic PDF is unable to split and resolve if possible.

# Screenshots

<details>
<summary></summary>

![Screenshot 2023-04-17 at 3 58 51 PM](https://user-images.githubusercontent.com/17851674/232596910-c560a56b-74ff-4272-9f91-d8d15237ec3b.png)

![Screenshot 2023-04-17 at 3 55 35 PM](https://user-images.githubusercontent.com/17851674/232596693-e561d1bd-24e1-4324-ad01-e1e2a4265dac.png)
</details>

# Testing Instructions and Sample Files

- Create a work and attach the Arabic pdf from the above-referenced work.
- Verify that PDF successfully splits into child pages ~~and appears in UV~~ (moved to https://github.com/scientist-softserv/iiif_print/issues/224)

# Notes

**Comment by laritakr** [comment]
Requires IiifPrint gem update. Blocked pending https://github.com/scientist-softserv/iiif_print/issues/224 fix.

**Comment by jillpe** [comment]
Handled in #313

**Comment by grahamjevon** [comment]
Hi @laritakr - the specific test instructions are successful. However, when I replicated the real life scenario of uploading two pdf files (the English book and the Arabic translation) at the point of adding [a new work](https://bl.bl-staging.notch8.cloud/concern/books/68c2aa73-7947-488c-bc96-695ac4b04f3f?locale=en), there was some unexpected behaviour. The most obvious sign of this is that the first split page displayed is page 039 (see screenshot below). This suggests that either some pages have not been split (yet?) or that something unexpected has happened to the ordering of the split pages.

![Image](https://user-images.githubusercontent.com/51366817/235616789-8aec2e82-e66e-49c3-aad5-8bd118c6f77c.png)

I notice there are split pages still appearing on the recent works feed despite the fact that I added this work about 24 hours ago (I'm assuming these are from my upload and not a subsequent SoftServ test). Is there another backlog?

![Image](https://user-images.githubusercontent.com/51366817/235618294-d9a7d205-8a9c-4ec2-8512-3ecf750bb4a0.png)

I wasn't sure whether to pass this ticket through QA and flag this unexpected behaviour as a different issue. I suspect you will know better whether this is related or distinct.

**Comment by laritakr** [comment]
Hi @grahamjevon This seems to be a completely separate issue, and also recently happened with another client as well. I'm really stumped on it but haven't had time yet to track down a cause - these randomly occurring issues are tough to duplicate and trace! 

We definitely need a new ticket for this behavior.

**Comment by grahamjevon** [comment]
Thanks @laritakr  - In that case I will pass this ticket through QA and I have created another ticket for this new issue #401.
