### ISSUE TITLE
unexplained pdf split issue

### ISSUE THREAD

**Issue by grahamjevon** [scientist-softserv/britishlibrary#401]
While testing #385, I encountered the following error, which @laritakr said had also been identified by another client.

When I replicated the real life scenario of uploading two pdf files (the English book and the Arabic translation) at the point of adding [a new work](https://bl.bl-staging.notch8.cloud/concern/books/68c2aa73-7947-488c-bc96-695ac4b04f3f?locale=en), there was some unexpected behaviour. The most obvious sign of this is that the first split page displayed is page 039 (see screenshot below). This suggests that either some pages have not been split (yet?) or that something unexpected has happened to the ordering of the split pages.

![Image](https://user-images.githubusercontent.com/51366817/235961702-74eab452-05f3-4810-be85-9e71f37976f6.png)

I notice there are split pages still appearing on the recent works feed despite the fact that I added this work about 24 hours ago (I'm assuming these are from my upload and not a subsequent SoftServ test). Is there another backlog?

![Image](https://user-images.githubusercontent.com/51366817/235961753-622ef10d-72b9-4fce-817c-9c4e75f89965.png)

# Notes

- This was identified as being caused by a race condition between PDF splitting of the first PDF on a work, and attaching the fileset of the second PDF on the work. 
- It is solved by reworking the create relationships job to lock the parent so it can't be changed incorrectly, and indexing the child works and file sets at the appropriate point in time.

# Testing Instructions

- Create a work with **two large PDF files** (like the files from the work Graham mentioned above)
- Verify that the pages on the parent work's show page and the universal viewer begin with page 1 of the first PDF added. (The bug was causing the first xx pages of the first PDF to lose their relationship to the parent.)

**Comment by laritakr** [comment]
This [iiif_print commit](https://github.com/scientist-softserv/iiif_print/pull/202) looks particularly suspicious given the reported behavior and may be a place to start looking.

**Comment by jillpe** [comment]
SoftServ QA: PASS!
Work URL: https://mola.bl-staging.notch8.cloud/concern/articles/3a3e4542-ec27-4748-93ea-3fad5a0c3b05?locale=en

Files Used:
[1993_092_192503.READER.pdf](https://github.com/scientist-softserv/britishlibrary/files/11520624/1993_092_192503.READER.pdf)



[1993_092_192503.pdf](https://github.com/scientist-softserv/britishlibrary/files/11520617/1993_092_192503.pdf)


https://github.com/scientist-softserv/britishlibrary/assets/84697174/f6ea918b-16ee-4715-be55-136d5f496521

**Comment by grahamjevon** [comment]
Passes BL QA - successfully uploaded the English and Arabic versions of Remote Capture book where the error was first recorded. UV and list of items both look as expected.
