### ISSUE TITLE
Add XML property "record_level_file_version_declaration" to work models

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#413]
# Summary
BL would like all methods of adding metadata to be equal, thus the XML ETD parser should also cater to Plan S work. To bridge the gap between the CSV and XML parsers, the `record_level_file_version_declaration` property should be added to the XML.

https://assaydepot.slack.com/archives/C0313NK2LJ0/p1683887768605789

#Accepted Criteria
- [ ] `record_level_file_version_declaration` property is on the XML

# Notes

**Comment by ShanaLMoore** [comment]
We need to know what the bulkrax field mappings should be for the XML parser. 

@grahamjevon to follow up after consulting with Jenny and Heather.

**Comment by jillpe** [comment]
Per client meeting 2023-05-16, uketd does not have a method to map this rn, so we will close this issue
