### ISSUE TITLE
Prod deploy + rake task

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#420]
# Story

LaRita has a rake task that we need to run, when we deploy everything to prod. So that we don't forget to run it, Rob's suggestion was to create a migration to trigger it. When the deploy runs db:migrate, the rake task will be executed. 

# Acceptance Criteria

- [ ] a deploy should trigger LaRita's [rake task](https://github.com/scientist-softserv/britishlibrary/commit/c69e3711cae530bc816cbee6988fc998f796e858). (Confirm with LaRita)

# Testing Instructions and Sample Files

- test by deploying to staging and verify that it runs.

**Comment by laritakr** [comment]
Add a migration:
```
def up
  SherpaApiFunderService.process_Funders(export: true, update: true)
end
```

**Comment by laritakr** [comment]
Passes QA: Verified that migration ran on staging upon deploy.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/17851674/4350c59e-f3c1-434f-b913-6398b8c60bee)
