### ISSUE TITLE
🐛 Update Bulkrax to bring in relationship job fix

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/britishlibrary#424]
# Story

After fixing Bulkrax, update gem in British Library.
- https://github.com/samvera-labs/bulkrax/issues/810

# Acceptance Criteria

- [ ] Bulkrax gem is updated to include fix from above-linked Bulkrax ticket.

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

- As this is an update from Bulkrax 5.1 to 5.2.x, test import and export to verify that both continue to behave as expected. There are a number of behind-the-scenes changes but very little should be visible. 
- Ticket is complete if import and export work as before.

# Notes

**Comment by jillpe** [comment]
SoftServ QA: PASS!

Import URL: https://mola.bl-staging.notch8.cloud/concern/articles/3a3e4542-ec27-4748-93ea-3fad5a0c3b05?locale=en

Import behavior was as expected

https://github.com/scientist-softserv/britishlibrary/assets/84697174/1ca2f2c2-2c5e-4c2f-939a-89d4875b0e0a


CSV Export URL: https://mola.bl-staging.notch8.cloud/exporters/27?locale=en
CSV Export File: 
[export_27_36_1.zip](https://github.com/scientist-softserv/britishlibrary/files/11520674/export_27_36_1.zip)
