### ISSUE TITLE
🐛 UV Download option - error message

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#429]
# Summary
reference: 
- https://github.com/scientist-softserv/britishlibrary/issues/313#issuecomment-1559627453

When I try to download a jpg, I get an error message.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/258afe25-a63b-42bb-a0c1-10127799d0ff)

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/bfa23ade-6fa6-4327-87d2-b4f5e0cd91bb)

# Acceptance Criteria
- [ ] As a logged in user, I can download a jpg without getting an error message
- [ ] We removed the low res option. Only the high res option should be available and a user can download it without error. 

# Testing Instructions
On staging, visit [this work/UV](https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/articles/3a3e4542-ec27-4748-93ea-3fad5a0c3b05/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json)
Click on the download button at the bottom of the the UV. see screenshot below
A user should be able to download any options available there, successfully. 

BEFORE: 
<img width="1149" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/10081604/4741b1f4-913a-4b77-b9ac-3386ba075706">

AFTER: 
Only the high res option should be available. A user should be able to download it without errors.

**Comment by jillpe** [comment]
User was logged in

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- work's UV: https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/articles/3a3e4542-ec27-4748-93ea-3fad5a0c3b05/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json
- work's download page: https://jwvkwtotuzhmc4olezwhmwtqym0yrftj.lambda-url.eu-west-1.on.aws/iiif/2/94798412d4b5f9cfc8175340e94eb8b301a540fe/full/3102,/0/default.jpg

<details><summary>Only the high res download option is available</summary>

![mola bl-staging notch8 clouduvuv html#manifest=mola bl-staging notch8 cloudconcernarticles3a3e4542-ec27-4748-93ea-3fad5a0c3b05manifest config=mola bl-staging notch8 clouduvuv-config json 2023-05-26 at 1 21 04 PM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/92f7a66c-820f-43ec-8c02-900034b97514)
![default jpg (3102×4340) 2023-05-26 at 2 22 40 PM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/cd662319-6fcb-4e09-a2e3-7fe23e50a657)


</details>

**Comment by grahamjevon** [comment]
This does not pass BL QA. I added [a work on staging](https://bl.bl-staging.notch8.cloud/concern/books/707033f9-2e2d-42ae-9155-70c5c205242c?locale=en) and when I try to download the page in UV, I still get the same error.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/57d51625-1d03-44ae-ac65-09a73257500a)

When I try to download the "(jpg)" option I get the error below. When I try to download the "(?)" option, it downloads successfully.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/4a6f4b3f-25af-4c37-ba97-e4d97a4d2a09)

**Comment by kirkkwang** [comment]
@grahamjevon That's weird, i purposefully hid that option and when i visited your page I don't see it, i'm curious how you're seeing it

<img width="436" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/19597776/6ece7987-2bd9-49a0-972f-646aaa41b046">

**Comment by grahamjevon** [comment]
@kirkkwang It looks like you are right - I don't see this option in incognito mode

**Comment by kirkkwang** [comment]
@grahamjevon thanks for checking that, unfortunately there's not much we can do about a user's cached data, it'll just have to expire on its own or get cleared.  If that is the situation, does this pass QA?

**Comment by grahamjevon** [comment]
yes - I'll pass it through.
