### ISSUE TITLE
UV page metadata - filename and page number would be very useful additions

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#431]
# Summary
relates to: #313 
In the "page" portion of the metadata, it would be really useful to show the filename of the pdf that is being viewed. And to show the page number. In this example, the work has two pdfs. It would be helpful if the page metadata indicated which pdf this page was part of and therefore which pdf was currently being viewed.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/3efa0b02-19e7-4995-9c89-4d72b05ed115)

All of that information is in the name of the child work so hopefully that would be relatively easy to include.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/9875994b-0512-4d9e-bc9f-510927ccec73)

# Accepted Criteria
- [ ] filename of the pdf being viewed is shown in the 'page' portion of the metadata

# Testing Instructions
Create a work with a multi page PDF attachment (manually or via bulkrax). 
Visit the parent's UV. 
The UV should render the multiple pages of that PDF. Clicking on each one should show change the metadata panel and include the pdf's filename and page number of that page.

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

- [X] Create a work with a multi page PDF attachment (manually or via bulkrax): https://bl.bl-staging.notch8.cloud/concern/articles/d3b02852-3d1d-48e3-baed-545a1ceb3769?locale=en
- [X] Visit the parent's UV: https://bl.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://bl.bl-staging.notch8.cloud/concern/articles/d3b02852-3d1d-48e3-baed-545a1ceb3769/manifest&config=https://bl.bl-staging.notch8.cloud/uv/uv-config.json
- [X] The UV should render the multiple pages of that PDF. Clicking on each one should show change the metadata panel and include the pdf's filename and page number of that page.

## SCREENSHOTS
![image](https://github.com/scientist-softserv/britishlibrary/assets/10081604/82c0c960-2e2c-4074-b445-639d15fd95d6)


### UV (2 page pdf)
<img width="677" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/10081604/ad769de6-c882-4427-b4f7-b5fc4c30b825">

<img width="672" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/10081604/c4c60eb4-259b-4762-a75b-22663c680a21">
