### ISSUE TITLE
🎁 4. UV page metadata - Page Creator links to faceted search that includes child works

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#432]
# Summary
ref:

- #313

The child works are hidden from all other search results (including the faceted link from the creator in the work level metadata in the UV). We think they should be hidden from here too - that the page "creator" faceted search link should work exactly the same as the work "creator" faceted search link.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/280d7c81-3810-44fd-b9a1-7ec8abf12b26)

# Accepted Criteria
- [ ] Page 'creator' links to the faceted search that does NOT include child works

# Testing Instructions
- [ ] Navigate to a work that has a child work attached
- [ ] Click 'View files in viewer'
- [ ] Once in the UV, open the 'More Information' panel on the right side of the viewer
- [ ] Under 'Page' in the panel, click the facet links to navigate to the search results page
- [ ] On the search results page, verify no child works are displayed in the search results

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- work show page: https://bl.bl-staging.notch8.cloud/concern/generic_works/fe053748-b8ef-4b94-ad7c-aa0f5d2dae24?locale=en
- work in UV: https://bl.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://bl.bl-staging.notch8.cloud/concern/generic_works/fe053748-b8ef-4b94-ad7c-aa0f5d2dae24/manifest&config=https://bl.bl-staging.notch8.cloud/uv/uv-config.json

<details><summary>Clicking a creator facet from the UV leads to a search </summary>

![bl bl-staging notch8 clouduvuv html#manifest=bl bl-staging notch8 cloudconcerngeneric_worksfe053748-b8ef-4b94-ad7c-aa0f5d2dae24manifest config=bl bl-staging notch8 clouduvuv-config json 2023-05-25 at 9 08 08 AM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/c713f8bc-d4e5-41ce-a3f9-289a2a7ef483)
![Index Catalog BL Staging 2023-05-25 at 9 08 20 AM](https://github.com/scientist-softserv/britishlibrary/assets/29311858/ff144a20-9026-4d69-8e23-89ecc6c70f49)
</details>
