### ISSUE TITLE
🐛 Bug: Reindex funders job

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#440]
# Story
[This work](https://kew.iro.bl.uk/concern/articles/b551d066-a4f6-4543-87e6-2fe81d578ad0) gave an indexing error during the PlanSFunder initial migration. When an indexing error occurs, the ReindexFundersJob will retry forever. 

```RSolr::Error::Http - 400 Bad Request Error: { "responseHeader":{ "rf":1, "status":400, "QTime":4}, "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException"], "msg":"Exception writing document id b551d066-a4f6-4543-87e6-2fe81d578ad0 to the index; possible analysis error: Document contains at least one immense term in field=\"suggest\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. ```

Need to either cancel job and then run manually after solution is found, or resolve this work and let it continue. It may be a good idea to rescue the error and continue the job.

Job to run is: `ReindexFundersJob.perform_later(dois: @updated_funder_dois)` with parameter below

```
"dois"=>["10.13039/100005393", "10.13039/501100002341", "10.13039/501100011858", "10.13039/501100001665", "10.13039/100018231", "10.13039/501100000267", "10.13039/501100002428", "10.13039/100000865", "10.13039/501100000268", "10.13039/501100000269", "10.13039/501100000266", "10.13039/100010661", "10.13039/501100006636", "10.13039/501100001866", "10.13039/501100003151", "10.13039/501100000156", "10.13039/100008240", "10.13039/501100001862", "10.13039/501100001871", "10.13039/501100010300", "10.13039/100000011", "10.13039/501100006041", "10.13039/501100000265", "10.13039/501100004281", "10.13039/501100000270", "10.13039/501100003246", "10.13039/501100005416", "10.13039/501100004472", "10.13039/501100001711", "10.13039/501100001602", "10.13039/501100000271", "10.13039/501100004329", "10.13039/501100001322", "10.13039/501100011730", "10.13039/100014013", "10.13039/501100001858", "10.13039/100004423", "10.13039/100004440"]
```

# Expected Behavior Before Changes
Job retries forever due to errors.

# Expected Behavior After Changes
The reindex funders job will complete normally.

# Screenshots / Video

<details>
<summary>Initial error</summary>

![Screenshot 2023-05-25 at 11 28 56 AM](https://github.com/scientist-softserv/britishlibrary/assets/17851674/2d003672-807d-4dd3-97d8-10ac3eb02222)
</details>

# Testing Instructions and Sample Files

- No testing is needed, as the job completed after the hotfix deploy. 
- Additional tickets were created as detailed in the notes below.

# Notes

Rails logging did not capture the expected log of error(s), which is apparently a known issue with Sidekiq and [a new ticket was created](https://github.com/scientist-softserv/britishlibrary/issues/443). But the job did complete normally. 

An attempted Solr config change did not affect the ability to index the work with the issue. This work cannot be indexed upon save via the UI. This has been reported as a [separate bug](https://github.com/scientist-softserv/britishlibrary/issues/442).

**Comment by ShanaLMoore** [comment]
We added a rescue statement so that the reindex job continues after errors. We reindexed prod already.
