### ISSUE TITLE
🦄 Spike: Estimate for British Library

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#448]
# Summary
In consideration for future work, BL would like an estimate for an admin dashboard filter. 

1. Currently, all child works show up in the admin dashboard and make it difficult to find the works they are looking for. They do want to keep child works in the dashboard because they want to be able to see them, but they want a filtering system to be able to narrow down the results. 

Ideas brainstormed in client meeting:
- Admin dashboard filter to filter out certain work types or select the work types you want to appear

2. The second piece they wanted estimated was on having the ability to hide child works on a show page if not logged and displaying them when logged in.

# Accepted Criteria
- [ ] Amount of hours or points for task established
- [ ] Hours or points translated to cost
- [ ] Estimate sent over to BL

**Comment by ShanaLMoore** [comment]
THIS IS NOT AN IMPLEMENTATION TICKET.

**Comment by ShanaLMoore** [comment]
Whoever picks this up, tag Jill.

**Comment by ShanaLMoore** [comment]
# hide child works on a show page if not logged

ideas:
